### ISSUE TITLE
Build for 0.6.5.8 fails on Fedora 25 after kernel update to 4.9.3

### ISSUE THREAD

**Issue by phaedrus77** [zfsonlinux/zfs#5610]
After the installation of the kernel update to 4.9.3 on FC25 building spl and zfs 0.6.5.8 fails.
Looks like GROUPT_AT and NGROUPS_SMALL disappeared from the kernel source (include/linux/cred.h):

 CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-xdr.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-atomic.o
In file included from /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:27:0:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c: In function ‘cr_groups_search’:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:53:20: error: implicit declaration of function ‘GROUP_AT’ [-Werror=implicit-function-declaration]
       KGID_TO_SGID(GROUP_AT(group_info, mid));
                    ^
/var/lib/dkms/spl/0.6.5.8/build/include/sys/cred.h:52:38: note: in definition of macro ‘KGID_TO_SGID’
 #define KGID_TO_SGID(x)  (__kgid_val(x))
                                      ^
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:53:20: error: incompatible type for argument 1 of ‘__kgid_val’
       KGID_TO_SGID(GROUP_AT(group_info, mid));
                    ^
/var/lib/dkms/spl/0.6.5.8/build/include/sys/cred.h:52:38: note: in definition of macro ‘KGID_TO_SGID’
 #define KGID_TO_SGID(x)  (__kgid_val(x))
                                      ^
In file included from ./include/linux/stat.h:19:0,
                 from ./include/linux/module.h:10,
                 from /var/lib/dkms/spl/0.6.5.8/build/include/sys/cred.h:28,
                 from /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:27:
./include/linux/uidgid.h:38:21: note: expected ‘kgid_t {aka struct <anonymous>}’ but argument is of type ‘int’
 static inline gid_t __kgid_val(kgid_t gid)
                     ^~~~~~~~~~
In file included from /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:27:0:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c: In function ‘crgetgroups’:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:107:26: error: ‘struct group_info’ has no member named ‘blocks’
  gids = KGIDP_TO_SGIDP(gi->blocks[0]);
                          ^
/var/lib/dkms/spl/0.6.5.8/build/include/sys/cred.h:55:30: note: in definition of macro ‘KGIDP_TO_SGIDP’
 #define KGIDP_TO_SGIDP(x) (&(x)->val)
                              ^
cc1: some warnings being treated as errors
scripts/Makefile.build:293: recipe for target '/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.o' failed
make[5]: *** [/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.o] Error 1
make[5]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-tsd.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-list.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-generic.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-zlib.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-linux.o
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c: In function ‘splat_cred_test3’:
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:191:20: error: ‘NGROUPS_SMALL’ undeclared (first use in this function)
  gi = groups_alloc(NGROUPS_SMALL);
                    ^~~~~~~~~~~~~
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:191:20: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:203:3: error: implicit declaration of function ‘GROUP_AT’ [-Werror=implicit-function-declaration]
   GROUP_AT(gi, i) = make_kgid(current_user_ns(), tmp_gid);
   ^~~~~~~~
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:203:19: error: lvalue required as left operand of assignment
   GROUP_AT(gi, i) = make_kgid(current_user_ns(), tmp_gid);
                   ^
cc1: some warnings being treated as errors
scripts/Makefile.build:293: recipe for target '/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.o' failed
make[5]: *** [/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.o] Error 1
make[5]: *** Waiting for unfinished jobs....
scripts/Makefile.build:544: recipe for target '/var/lib/dkms/spl/0.6.5.8/build/module/spl' failed
make[4]: *** [/var/lib/dkms/spl/0.6.5.8/build/module/spl] Error 2
make[4]: *** Waiting for unfinished jobs....
scripts/Makefile.build:544: recipe for target '/var/lib/dkms/spl/0.6.5.8/build/module/splat' failed
make[4]: *** [/var/lib/dkms/spl/0.6.5.8/build/module/splat] Error 2
Makefile:1494: recipe for target '_module_/var/lib/dkms/spl/0.6.5.8/build/module' failed
make[3]: *** [_module_/var/lib/dkms/spl/0.6.5.8/build/module] Error 2
make[3]: Leaving directory '/usr/src/kernels/4.9.3-200.fc25.x86_64'
Makefile:11: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/spl/0.6.5.8/build/module'
Makefile:588: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/spl/0.6.5.8/build'
Makefile:469: recipe for target 'all' failed
make: *** [all] Error 2

Is this already addressed in the 0.7-branch?

 Bernd

**Comment by gmelikov** [comment]
Please fill issue template and search for similar issue next time first. 0.6.5.8 doesn't support this kernel, it's already fixed in master.

**Comment by phaedrus77** [comment]
I'm sorry I didn't find while browsing the issue tracker. When is an updated rpm for FC25 expected?

**Comment by behlendorf** [comment]
I'll see about applying the needed fixing and putting out a minor update for FC25.

**Comment by zfs-fan** [comment]
Same problem on FC24 with recent kernel 4.9.x (at least 4.9.4. and 4.9.5):

In file included from /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:27:0:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c: In function ‘cr_groups_search’:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:53:20: error: implicit declaration of function ‘GROUP_AT’ [-Werror=implicit-function-declaration]
       KGID_TO_SGID(GROUP_AT(group_info, mid));
                    ^

**Comment by behlendorf** [comment]
Alright, the Fedora 24 repo can get an update as well.

**Comment by bitshark** [comment]
Same issue on Void Linux with kernel 4.9.0_1
```
dkms install -m spl -v 0.6.5.8 -k 4.9.0_1
[...]
config.status: executing depfiles commands
config.status: executing libtool commands

Building module:
cleaning build area....
make KERNELRELEASE=4.9.0_1......(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.9.0_1 (x86_64)
Consult /var/lib/dkms/spl/0.6.5.8/build/make.log for more information.
```

from make.log
```
make[2]: Entering directory '/var/lib/dkms/spl/0.6.5.8/build/module'
make -C /lib/modules/4.9.0_1/build SUBDIRS=`pwd`  CONFIG_SPL=m modules
make[3]: Entering directory '/usr/src/kernel-headers-4.9.0_1'
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-vmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-thread.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-taskq.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-rwlock.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-vnode.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-err.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-kobj.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-generic.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-atomic.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-mutex.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-kstat.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-condvar.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-xdr.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.o
In file included from /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:27:0:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c: In function 'cr_groups_search':
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:53:20: error: implicit declaration of function 'GROUP_AT' [-Werror=implicit-funct
ion-declaration]
       KGID_TO_SGID(GROUP_AT(group_info, mid));
/var/lib/dkms/spl/0.6.5.8/build/include/sys/cred.h:52:38: note: in definition of macro 'KGID_TO_SGID'
 #define KGID_TO_SGID(x)  (__kgid_val(x))
                                      ^
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:53:20: error: incompatible type for argument 1 of '__kgid_val'
       KGID_TO_SGID(GROUP_AT(group_info, mid));
                    ^
/var/lib/dkms/spl/0.6.5.8/build/include/sys/cred.h:52:38: note: in definition of macro 'KGID_TO_SGID'
 #define KGID_TO_SGID(x)  (__kgid_val(x))
                                      ^
In file included from ./include/linux/stat.h:19:0,
                 from ./include/linux/module.h:10,
                 from /var/lib/dkms/spl/0.6.5.8/build/include/sys/cred.h:28,
                 from /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:27:
./include/linux/uidgid.h:38:21: note: expected 'kgid_t {aka struct <anonymous>}' but argument is of type 'int'
 static inline gid_t __kgid_val(kgid_t gid)
                     ^~~~~~~~~~
In file included from /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:27:0:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c: In function 'crgetgroups':
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:107:26: error: 'struct group_info' has no member named 'blocks'
  gids = KGIDP_TO_SGIDP(gi->blocks[0]);
                          ^
/var/lib/dkms/spl/0.6.5.8/build/include/sys/cred.h:55:30: note: in definition of macro 'KGIDP_TO_SGIDP'
 #define KGIDP_TO_SGIDP(x) (&(x)->val)
                              ^
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:294: /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.o] Error 1
make[4]: *** [scripts/Makefile.build:544: /var/lib/dkms/spl/0.6.5.8/build/module/spl] Error 2

```
