### ISSUE TITLE
Compilation error kernel 4.14.13 and zfs 0.7-release

### ISSUE THREAD

**Issue by voidzero** [zfsonlinux/zfs#7069]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Funtoo Linux (Gentoo derivative)
Linux Kernel                 | 4.14.13
Architecture                 | x86_64
ZFS Version                  | 0.7-release
SPL Version                  | 0.7-release
GCC version                  | 7.1.0

Compilation output:

```
fs/zfs/zfs/metaslab.c:1052:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_create,
  ^~~~~~~~~~~~~~~~~~
fs/zfs/zfs/metaslab.c:1052:2: note: (near initialization for ‘metaslab_rt_ops’)
fs/zfs/zfs/metaslab.c:1052:2: error: invalid initializer
fs/zfs/zfs/metaslab.c:1052:2: note: (near initialization for ‘metaslab_rt_ops.<anonymous>’)
fs/zfs/zfs/metaslab.c:1053:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_destroy,
  ^~~~~~~~~~~~~~~~~~~
fs/zfs/zfs/metaslab.c:1053:2: note: (near initialization for ‘metaslab_rt_ops’)
fs/zfs/zfs/metaslab.c:1053:2: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
fs/zfs/zfs/metaslab.c:1053:2: note: (near initialization for ‘metaslab_rt_ops.rtop_add’)
fs/zfs/zfs/metaslab.c:1054:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_add,
  ^~~~~~~~~~~~~~~
fs/zfs/zfs/metaslab.c:1054:2: note: (near initialization for ‘metaslab_rt_ops’)
fs/zfs/zfs/metaslab.c:1055:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_remove,
  ^~~~~~~~~~~~~~~~~~
fs/zfs/zfs/metaslab.c:1055:2: note: (near initialization for ‘metaslab_rt_ops’)
fs/zfs/zfs/metaslab.c:1055:2: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
fs/zfs/zfs/metaslab.c:1055:2: note: (near initialization for ‘metaslab_rt_ops.rtop_destroy’)
fs/zfs/zfs/metaslab.c:1056:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_vacate
  ^~~~~~~~~~~~~~~~~~
fs/zfs/zfs/metaslab.c:1056:2: note: (near initialization for ‘metaslab_rt_ops’)
```

**Comment by kpande** [comment]
this is not related to 4.14.13, that runs fine here with 0.7

**Comment by voidzero** [comment]
Ok, might be a gcc version issue. Trying 6.3.0 now.

**Comment by kpande** [comment]
my system compiles 4.14.13 and 0.7 with 5.4.0 (on Gentoo) which is probably considered unacceptably ancient - if this helps narrow down the problem.

**Comment by voidzero** [comment]
gcc 6.3.0 also fails. Same output. Note: I am building zfs into the kernel - not as separate modules.

**Comment by kpande** [comment]
@prometheanfire also builds in-kernel

**Comment by maxximino** [comment]
@voidzero I believe you have:
General setup > GCC plugins > Randomize layout of sensitive kernel structures (CONFIG_GCC_PLUGIN_RANDSTRUCT) set to Y .
Without it, it should build.
Thanks for filing the bug.

**Comment by rincebrain** [comment]
@maxximino zfsonlinux/spl#654 is a similar bug, you could probably examine that to see if a similar correction is needed for this to build here.

**Comment by voidzero** [comment]
@maxximino I did indeed have that enabled, and it compiles now that I disabled it. Thank you. Is this something that will be supported in the future? Any idea?

**Comment by osti** [comment]
This might get more problematic if stock kernels include more and more of meltdown mitigation.

**Comment by prometheanfire** [comment]
I've been running with the following for about a year just fine.  I build from git master though...

```
CONFIG_GCC_PLUGIN_RANDSTRUCT=y
CONFIG_GCC_PLUGIN_RANDSTRUCT_PERFORMANCE=y
```

**Comment by twoertwein** [comment]
I also encounter the same issue when trying to compile zfs into the kernel (ZFS 0.7.7 into 4.14.28 with GCC 7.3.1). Disabling `CONFIG_GCC_PLUGIN_RANDSTRUCT` 'solves' the issue but that is not a real solution to this problem!

**Comment by behlendorf** [comment]
Sorry, we lost track of this one.  We'll sort it out in the next point release, it was incidentally addressed is master by commit d4a72f23863382bdf6d0ae33196f5b5decbc48fd.

**Comment by tonyhutter** [comment]
Can you try rebuilding with 0.7.9? (just released today)

**Comment by twoertwein** [comment]
sorry, it still doesn't seem to work with 0.7.9 (gcc 7.3.1, linux 4.14.40)

```
fs/zfs/zfs/metaslab.c:1052:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_create,
  ^~~~~~~~~~~~~~~~~~
fs/zfs/zfs/metaslab.c:1052:2: note: (near initialization for ‘metaslab_rt_ops’)
fs/zfs/zfs/metaslab.c:1052:2: error: invalid initializer
fs/zfs/zfs/metaslab.c:1052:2: note: (near initialization for ‘metaslab_rt_ops.<anonymous>’)
fs/zfs/zfs/metaslab.c:1053:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_destroy,
  ^~~~~~~~~~~~~~~~~~~
fs/zfs/zfs/metaslab.c:1053:2: note: (near initialization for ‘metaslab_rt_ops’)
fs/zfs/zfs/metaslab.c:1053:2: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
fs/zfs/zfs/metaslab.c:1053:2: note: (near initialization for ‘metaslab_rt_ops.rtop_add’)
fs/zfs/zfs/metaslab.c:1054:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_add,
  ^~~~~~~~~~~~~~~
fs/zfs/zfs/metaslab.c:1054:2: note: (near initialization for ‘metaslab_rt_ops’)
fs/zfs/zfs/metaslab.c:1054:2: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
fs/zfs/zfs/metaslab.c:1054:2: note: (near initialization for ‘metaslab_rt_ops.rtop_create’)
fs/zfs/zfs/metaslab.c:1055:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_remove,
  ^~~~~~~~~~~~~~~~~~
fs/zfs/zfs/metaslab.c:1055:2: note: (near initialization for ‘metaslab_rt_ops’)
fs/zfs/zfs/metaslab.c:1055:2: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
fs/zfs/zfs/metaslab.c:1055:2: note: (near initialization for ‘metaslab_rt_ops.rtop_vacate’)
fs/zfs/zfs/metaslab.c:1056:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_vacate
  ^~~~~~~~~~~~~~~~~~
fs/zfs/zfs/metaslab.c:1056:2: note: (near initialization for ‘metaslab_rt_ops’)
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:328: fs/zfs/zfs/metaslab.o] Error 1
make[2]: *** [scripts/Makefile.build:587: fs/zfs/zfs] Error 2
make[1]: *** [scripts/Makefile.build:587: fs/zfs] Error 2
make: *** [Makefile:1040: fs] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by gyakovlev** [comment]
I confirm.
Still broken
4.16.8
zfs-kmod-0.7.9
CONFIG_GCC_PLUGIN_RANDSTRUCT=y
CONFIG_GCC_PLUGIN_RANDSTRUCT_PERFORMANCE=y

```gcc
/tmp/portage/sys-fs/zfs-kmod-0.7.9/work/zfs-0.7.9/module/zfs/metaslab.c:1052:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]                                                                                                                                                                                     
  metaslab_rt_create,                                                                                                                                                                          
  ^~~~~~~~~~~~~~~~~~                                                                                                                                                                           
/tmp/portage/sys-fs/zfs-kmod-0.7.9/work/zfs-0.7.9/module/zfs/metaslab.c:1052:2: note: (near initialization for ‘metaslab_rt_ops’)                                                              
/tmp/portage/sys-fs/zfs-kmod-0.7.9/work/zfs-0.7.9/module/zfs/metaslab.c:1052:2: error: invalid initializer                                                                                     
/tmp/portage/sys-fs/zfs-kmod-0.7.9/work/zfs-0.7.9/module/zfs/metaslab.c:1052:2: note: (near initialization for ‘metaslab_rt_ops.<anonymous>’)                                                  
/tmp/portage/sys-fs/zfs-kmod-0.7.9/work/zfs-0.7.9/module/zfs/metaslab.c:1053:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]                                                                                                                                                                                     
  metaslab_rt_destroy,                                                                                                                                                                         
  ^~~~~~~~~~~~~~~~~~~
/tmp/portage/sys-fs/zfs-kmod-0.7.9/work/zfs-0.7.9/module/zfs/metaslab.c:1053:2: note: (near initialization for ‘metaslab_rt_ops’)                                                             
/tmp/portage/sys-fs/zfs-kmod-0.7.9/work/zfs-0.7.9/module/zfs/metaslab.c:1054:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_add,
  ^~~~~~~~~~~~~~~
/tmp/portage/sys-fs/zfs-kmod-0.7.9/work/zfs-0.7.9/module/zfs/metaslab.c:1054:2: note: (near initialization for ‘metaslab_rt_ops’)                                                             
/tmp/portage/sys-fs/zfs-kmod-0.7.9/work/zfs-0.7.9/module/zfs/metaslab.c:1055:2: error: positional initialization of field in ‘struct’ declared with ‘designated_init’ attribute [-Werror=designated-init]
  metaslab_rt_remove,
  ^~~~~~~~~~~~~~~~~~```

**Comment by gyakovlev** [comment]
Compiles and works with the following patch.
Use at your own risk, I don't really know what I'm doing =)

```patch
diff --git a/module/zfs/metaslab.c b/module/zfs/metaslab.c
index 5e413c0..209b685 100644
--- a/module/zfs/metaslab.c
+++ b/module/zfs/metaslab.c
@@ -1049,11 +1049,11 @@ metaslab_rt_vacate(range_tree_t *rt, void *arg)
 }
 
 static range_tree_ops_t metaslab_rt_ops = {
-       metaslab_rt_create,
-       metaslab_rt_destroy,
-       metaslab_rt_add,
-       metaslab_rt_remove,
-       metaslab_rt_vacate
+       .rtop_create = metaslab_rt_create,
+       .rtop_destroy = metaslab_rt_destroy,
+       .rtop_add = metaslab_rt_add,
+       .rtop_remove = metaslab_rt_remove,
+       .rtop_vacate = metaslab_rt_vacate
 };
 
 /*
```

**Comment by loli10K** [comment]
This should be fixed by https://github.com/zfsonlinux/zfs/commit/30d8b8570243fe5b944f26a964cf5204cb1e71e0, closing.
