### PR TITLE
Linux 4.3 compat: bio_end_io_t / BIO_UPTODATE

### LINKED ISSUE #3799: Can't compile with 4.3-rc1 kernel
Tested with git master:

  CC [M]  /var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.o
In file included from include/linux/bitops.h:36:0,
                 from include/linux/kernel.h:10,
                 from include/linux/list.h:8,
                 from include/linux/module.h:9,
                 from /usr/src/spl-0.6.4.2/include/sys/sysmacros.h:28,
                 from /usr/src/spl-0.6.4.2/include/sys/types.h:29,
                 from /var/lib/dkms/zfs/0.6.4.2/build/include/sys/zfs_context.h:37,
                 from /var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:29:
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c: In function 'vdev_disk_physio_completion':
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:437:30: error: 'BIO_UPTODATE' undeclared (first use in this function)
  if (error == 0 && !test_bit(BIO_UPTODATE, &bio->bi_flags))
                              ^
./arch/x86/include/asm/bitops.h:336:25: note: in definition of macro 'test_bit'
  (__builtin_constant_p((nr))  \
                         ^
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:437:30: note: each undeclared identifier is reported only once for each function it appears in
  if (error == 0 && !test_bit(BIO_UPTODATE, &bio->bi_flags))
                              ^
./arch/x86/include/asm/bitops.h:336:25: note: in definition of macro 'test_bit'
  (__builtin_constant_p((nr))  \
                         ^
./arch/x86/include/asm/bitops.h:337:29: warning: passing argument 2 of 'constant_test_bit' from incompatible pointer type [-Wincompatible-pointer-types]
   ? constant_test_bit((nr), (addr)) \
                             ^
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:437:21: note: in expansion of macro 'test_bit'
  if (error == 0 && !test_bit(BIO_UPTODATE, &bio->bi_flags))
                     ^
./arch/x86/include/asm/bitops.h:308:28: note: expected 'const volatile long unsigned int *' but argument is of type 'unsigned int *'
 static __always_inline int constant_test_bit(long nr, const volatile unsigned long *addr)
                            ^
./arch/x86/include/asm/bitops.h:338:29: warning: passing argument 2 of 'variable_test_bit' from incompatible pointer type [-Wincompatible-pointer-types]
   : variable_test_bit((nr), (addr)))
                             ^
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:437:21: note: in expansion of macro 'test_bit'
  if (error == 0 && !test_bit(BIO_UPTODATE, &bio->bi_flags))
                     ^
./arch/x86/include/asm/bitops.h:314:19: note: expected 'const volatile long unsigned int *' but argument is of type 'unsigned int *'
 static inline int variable_test_bit(long nr, volatile const unsigned long *addr)
                   ^
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c: In function '__vdev_disk_physio':
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:579:28: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   dr->dr_bio[i]->bi_end_io = vdev_disk_physio_completion;
                            ^
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c: In function 'vdev_disk_io_flush':
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:660:17: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
  bio->bi_end_io = vdev_disk_io_flush_completion;
                 ^
scripts/Makefile.build:258: recipe for target '/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.o' failed
make[5]: *** [/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.o] Error 1
scripts/Makefile.build:403: recipe for target '/var/lib/dkms/zfs/0.6.4.2/build/module/zfs' failed
make[4]: *** [/var/lib/dkms/zfs/0.6.4.2/build/module/zfs] Error 2
Makefile:1378: recipe for target '_module_/var/lib/dkms/zfs/0.6.4.2/build/module' failed
make[3]: *** [_module_/var/lib/dkms/zfs/0.6.4.2/build/module] Error 2
make[3]: Leaving directory '/usr/lib/modules/4.3.0-rc1-mainline/build'
Makefile:16: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.6.4.2/build/module'
Makefile:685: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.6.4.2/build'
Makefile:556: recipe for target 'all' failed
make: *** [all] Error 2

### PR DESCRIPTION
**Pull request by l1k**
This seems to be the only compat issue with 4.3 so far, I have it running fine now with 4.3-rc2. Let's see what the build bot says.

I refactored the code in `vdev_disk_physio_completion()` a bit in an attempt to retain readability. If you want anything changed do not hesitate to post a comment. Thanks.

One thing that struck me as odd is that `dio_request_t->dr_error` (and consequently `zio->io_error`) stores a *positive* errno. Is this a Solaris convention?

Fixes #3799

### CODE REVIEW

**Comment by l1k** [comment]
Hm, 37f9dac592bf5889c3efb305c48ac39b4c7dd140 (authored by @ryao) broke the build for pre 2.6.24 kernels because it assumes 2 arguments for `bio_endio()` and these older kernels used 3 arguments. This got merged into 0.6.5 and didn't show up on my machine because I'm still on 0.6.4. It's trivial to fix this for 4.3 but to fix it for pre 2.6.24 kernels I need to do some git archaeology first to understand what the size argument should be set to.

**Comment by behlendorf** [comment]
I'll need to take a more careful look but it looks reasonable.  A few quick comments.

> stores a positive errno. Is this a Solaris convention

Yes, I find it strange as well coming from a Linux background but Illumos never used negative errnos.  This means where the illumos code and Linux code need we often need to invert the logic.  The biggest place this happened is between the `zpl_*` wrappers which hook in the Linux VFS and the original `zfs_*` implementations of this functionality.  It's definitely something to keep in mind.

> broke the build for pre 2.6.24

This was done knowingly.  We only support back to 2.6.32 kernels to keep the amount of compatibility code and required testing to a reasonable level.  So don't worry about that.

**Comment by l1k** [comment]
Thanks a lot for the explanation and feedback @behlendorf.

I fixed the build breakage introduced by 37f9dac592bf5889c3efb305c48ac39b4c7dd140, though I'm not 100% certain if this works on these ancient kernels: The third argument to `bio_endio()` that was dropped with torvalds/linux@6712ecf8f648118c3363c142196418f89a510b90 indicates the amount of bytes successfully read/written. Unless I'm missing something, this cannot easily be determined in `zvol.c:zvol_request()` so I resorted to passing 0.

<blockquote>
This was done knowingly. We only support back to 2.6.32 kernels to keep the amount of compatibility code and required testing to a reasonable level. So don't worry about that.
</blockquote>

Hm, in that case we can either keep the patch as is and continue supporting these old kernels on a best effort basis, or I could rework the patch to drop support for the three argument `bio_endio()` entirely. Your call. :)

**Comment by behlendorf** [comment]
@l1k  our unstated policy has been to drop dead code like this so can you rework the patch to drop the three argument version.  Then I'll take another look at the patch.

**Comment by l1k** [comment]
@behlendorf: Voilà, sans support for 3 argument bio_endio().

I kept the small refactoring of `vdev_disk_physio_completion()` because I felt that it improves readability/clarity. But that's just me so if you want that or anything else changed just let me know. The alternative would have been to use the same approach as in `vdev_disk_io_flush_completion`, i.e. set `int error = bio->bi_error;` if `HAVE_1ARG_BIO_END_IO_T` is defined.

Build bot fails on 3 platforms but pull #3833 which you opened yesterday fails on those same platforms at the exact same checks so I assume this is not related to my patch. Notably `ubuntu-14.04-amd64-current-builder`, which uses 4.3 and thus doesn't compile for #3833, compiles fine now but fails on "test import". Sadly I can't find any hints in the stdio log as to the cause.

**Comment by l1k** [comment]
By the way, `vdev_disk_io_flush_completion()` does not check BIO_UPTODATE (unlike `vdev_disk_physio_completion`). Is this correct?

**Comment by behlendorf** [comment]
@l1k nice work, this LGTM.  I think the approach you settled on works and does make the code more readable.  Thanks for tackling this, it'll be nice to be caught back up to the kernel again.

As for the buildbot failures the two ztest failures are definitely not related to this change.  As for the import failure that's also to be expected because it due to the tip of master failing to build on the current builder.  Once this patch is merged that will be resolved.

Regarding `vdev_disk_io_flush_completion()` it problem should check BIO_UPTODATE as well but let's go for the minimal change here as you've done.  I should be able to get this merged today.

**Comment by behlendorf** [comment]
Merged as:

784a7fe Linux 4.3 compat: bio_end_io_t / BIO_UPTODATE

**Comment by ryao** [comment]
If anyone wants ZoL to reintroduce support pre-2.6.32 kernels and can produce patches that make it work in a maintainable manner, feel free to open a pull request.

The reason pre-2.6.32 support was dropped was because no one used it and maintaining support was becoming too arduous. The cleanup from removing support was a reduction of something like 3 to 4 thousand lines of code across both zfsonlinux/spl and zfsonlinux/spl. No one seemed to use those kernels such that the downsides of dropping support were virtually zero and in comparison to refactoring.

zfsonlinux/spl@ec18fe3ce8f27cfd86743f091d2d57e78dd8a5af showed that there can be ways to refactor code that reduce complexity while maintaining support for both old and new kernels. Barring kernel API limitations in older kernels that I do not recall, I would not consider reintroducing support for pre-2.6.32 kernels to be infeasible if one were willing to spend time on it. If someone were to do this, he likely should do it by picking a modern interface and reimplementing it for the places where it is not available so that the code is remains maintainable.

**Comment by ryao** [comment]
zfsonlinux/zfs@0f37d0c8bed442dd0d2c1b1dddd68653fa6eec66 might be a better example of that concept. Rather than dealing with a symbol being removed like that SPL patch did, this patch had to deal with an API change intended to make the kernel API better. The solution made the code cleaner by refactoring it to use the new interface and implementing a shim that allowed the same code to be used on older kernels.

**Comment by ryao** [comment]
After looking at the original patch that caused the change, that SPL patch was a refactoring of a patch that responded to API cleanup in mainline, torvalds/linux@79714f72d3b964611997de512cb29198c9f2dbbb. The new private API is really what we wanted for maintainability, but it was not immediately obvious that we could implement it ourselves due to loss of access to a string. The refactoring was done after the realization that the string's contents could be calculated via a basename operation on a string that we already had.

**Comment by l1k** [comment]
@behlendorf: In trying to find out why `vdev_disk_io_flush_completion()` doesn't check the `BIO_UPTODATE` flag while `vdev_disk_physio_completion()` does, I've realized that the check in the latter is obsolete: <a href="https://github.com/torvalds/linux/blob/64291f7db5bd8150a74ad2036f1037e6a0428df2/block/bio.c#L1797">`bio_endio()`</a> already checks the `BIO_UPTODATE` flag and sets `error = -EIO` before invoking the `->bi_end_io` callback, obviating the need that we check the flag once more. And it's been doing that since 2.6.24 (specifically torvalds/linux@9cc54d40b8ca). So we'd only need the additional `BIO_UPTODATE` check for pre 2.6.24 kernels which are no longer supported. This new commit thus drops the additional check. However somebody should doublecheck this in case I'm missing something.

@ryao: Thank you for these tips, I will keep that in mind when I need to fix future compat issues. (Which may happen sooner rather than later because I dev on the drivers/gpu subsystem and use a root zpool, so I'm bitten by compat issues very early.)
