### ISSUE TITLE
Conflicting type warning during build

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#6960]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  -
Distribution Version    |  -
Linux Kernel                 |  -
Architecture                 |  -
ZFS Version                  |  zfs-0.7.0-211-g4e9b156
SPL Version                  | spl-0.7.0-21-ged19bcc

### Describe the problem you're observing

Build failure introduced by commit c28a67733c68b5540968136a7aca9633146afaf9 in some environments.

### Describe how to reproduce the problem

```
./configure; make -s
```

### Include any warning/errors/backtraces from the system logs
```
In file included from ../../module/zcommon/zfs_fletcher_avx512.c:29:0:
../../lib/libspl/include/sys/frame.h:33:14: error: conflicting types for 'greg_t'
typedef long greg_t;
^
In file included from /usr/include/signal.h:360:0,
from /usr/include/sys/param.h:28,
from ../../lib/libspl/include/sys/param.h:30,
from ../../lib/libspl/include/sys/types.h:100,
from ../../include/linux/simd_x86.h:75,
from ../../module/zcommon/zfs_fletcher_avx512.c:27:
/usr/include/sys/ucontext.h:31:37: note: previous declaration of 'greg_t' was here
extension typedef long long int greg_t;
^
```
