### ISSUE TITLE
Bad return status for module build on kernel: 4.9.0-1.el7.elrepo.x86_64 (x86_64)

### ISSUE THREAD

**Issue by fffmmm** [zfsonlinux/zfs#5478]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Centos
Distribution Version    | 7
Linux Kernel                 | kernel-ml-4.9.0-1.el7.elrepo.x86_64
Architecture                 | x86_64
ZFS Version                  | zfs-0.6.5.8-1.el7.centos.x86_64
SPL Version                  | spl-0.6.5.8-1.el7.centos.x86_64

### Describe the problem you're observing

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.9.0-1.el7.elrepo.x86_64....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.9.0-1.el7.elrepo.x86_64 (x86_64)
Consult /var/lib/dkms/spl/0.6.5.8/build/make.log for more information.

### Describe how to reproduce the problem
  dkms install  spl/0.6.5.8 -k 4.9.0-1.el7.elrepo.x86_64
  dkms install  zfs/0.6.5.8 -k 4.9.0-1.el7.elrepo.x86_64

**Comment by fffmmm** [comment]
# cat /var/lib/dkms/spl/0.6.5.8/build/make.log
DKMS make.log for spl-0.6.5.8 for kernel 4.9.0-1.el7.elrepo.x86_64 (x86_64)
Tue Dec 13 19:03:23 CET 2016
make  all-recursive
make[1]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build'
Making all in include
make[2]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include'
Making all in fs
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/fs'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/fs'
Making all in linux
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/linux'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/linux'
Making all in rpc
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/rpc'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/rpc'
Making all in sharefs
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/sharefs'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/sharefs'
Making all in sys
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/sys'
Making all in fm
make[4]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/sys/fm'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/sys/fm'
Making all in fs
make[4]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/sys/fs'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/sys/fs'
Making all in sysevent
make[4]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/sys/sysevent'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/sys/sysevent'
make[4]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/sys'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/sys'
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/sys'
Making all in util
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/util'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/util'
Making all in vm
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include/vm'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include/vm'
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/include'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include'
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/include'
Making all in rpm
make[2]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/rpm'
Making all in generic
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/rpm/generic'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/rpm/generic'
Making all in redhat
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/rpm/redhat'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/rpm/redhat'
make[3]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/rpm'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/rpm'
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/rpm'
Making all in module
make[2]: Entering directory `/var/lib/dkms/spl/0.6.5.8/build/module'
make -C /lib/modules/4.9.0-1.el7.elrepo.x86_64/build SUBDIRS=`pwd`  CONFIG_SPL=m modules
make[3]: Entering directory `/usr/src/kernels/4.9.0-1.el7.elrepo.x86_64'
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-ctl.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-kmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-vmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-taskq.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-thread.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-taskq.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-random.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-rwlock.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-mutex.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-vnode.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-err.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-condvar.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-kobj.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-thread.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-generic.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-atomic.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-rwlock.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-mutex.o
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-generic.c:56:1: warning: missing braces around initializer [-Wmissing-braces]
 proc_t p0 = { 0 };
 ^
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-generic.c:56:1: warning: (near initialization for ‘p0.thread_info’) [-Wmissing-braces]
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-time.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-kstat.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-condvar.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-vnode.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-xdr.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-tsd.o
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c: In function ‘cr_groups_search’:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:53:7: error: implicit declaration of function ‘GROUP_AT’ [-Werror=implicit-function-declaration]
       KGID_TO_SGID(GROUP_AT(group_info, mid));
       ^
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:53:7: error: incompatible type for argument 1 of ‘__kgid_val’
In file included from ./include/linux/stat.h:19:0,
                 from ./include/linux/module.h:10,
                 from /var/lib/dkms/spl/0.6.5.8/build/include/sys/cred.h:28,
                 from /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:27:
./include/linux/uidgid.h:38:21: note: expected ‘kgid_t’ but argument is of type ‘int’
 static inline gid_t __kgid_val(kgid_t gid)
                     ^
In file included from /var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:27:0:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c: In function ‘crgetgroups’:
/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.c:107:26: error: ‘struct group_info’ has no member named ‘blocks’
  gids = KGIDP_TO_SGIDP(gi->blocks[0]);
                          ^
/var/lib/dkms/spl/0.6.5.8/build/include/sys/cred.h:55:30: note: in definition of macro ‘KGIDP_TO_SGIDP’
 #define KGIDP_TO_SGIDP(x) (&(x)->val)
                              ^
cc1: some warnings being treated as errors
make[5]: *** [/var/lib/dkms/spl/0.6.5.8/build/module/spl/spl-cred.o] Error 1
make[5]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-kobj.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-atomic.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-list.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-generic.o
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.o
make[4]: *** [/var/lib/dkms/spl/0.6.5.8/build/module/spl] Error 2
make[4]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-zlib.o
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c: In function ‘splat_cred_test3’:
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:191:20: error: ‘NGROUPS_SMALL’ undeclared (first use in this function)
  gi = groups_alloc(NGROUPS_SMALL);
                    ^
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:191:20: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:203:3: error: implicit declaration of function ‘GROUP_AT’ [-Werror=implicit-function-declaration]
   GROUP_AT(gi, i) = make_kgid(current_user_ns(), tmp_gid);
   ^
/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.c:203:19: error: lvalue required as left operand of assignment
   GROUP_AT(gi, i) = make_kgid(current_user_ns(), tmp_gid);
                   ^
cc1: some warnings being treated as errors
make[5]: *** [/var/lib/dkms/spl/0.6.5.8/build/module/splat/splat-cred.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [/var/lib/dkms/spl/0.6.5.8/build/module/splat] Error 2
make[3]: *** [_module_/var/lib/dkms/spl/0.6.5.8/build/module] Error 2
make[3]: Leaving directory `/usr/src/kernels/4.9.0-1.el7.elrepo.x86_64'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/dkms/spl/0.6.5.8/build'
make: *** [all] Error 2

**Comment by Kajanos87** [comment]
Hello, check this:
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.8

Supported Kernels

Compatible with 2.6.32 - 4.8 Linux kernels.

I have the same issue on Gentoo with zfs module 0.6.5.8

At the moment I have got module v0.7.0-rc2 and working well on kernel 4.9.
