### ISSUE TITLE
4.0-rc1 kernel issue

### ISSUE THREAD

**Issue by colorprint** [zfsonlinux/zfs#3128]
CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/zfs/../../module/zfs/arc.o
In file included from /var/lib/dkms/zfs/0.6.3/build/include/sys/zpl.h:35:0,
                 from /var/lib/dkms/zfs/0.6.3/build/module/zfs/../../module/zfs/arc.c:142:
/var/lib/dkms/zfs/0.6.3/build/include/linux/vfs_compat.h:77:1: error: conflicting types for 'bdi_setup_and_register'
 bdi_setup_and_register(
 ^
In file included from include/linux/blkdev.h:15:0,
                 from /usr/src/spl-0.6.3/include/sys/sunldi.h:33,
                 from /usr/src/spl-0.6.3/include/sys/sunddi.h:30,
                 from /usr/src/spl-0.6.3/include/sys/systm.h:28,
                 from /var/lib/dkms/zfs/0.6.3/build/include/sys/zfs_context.h:49,
                 from /var/lib/dkms/zfs/0.6.3/build/include/sys/spa.h:31,
                 from /var/lib/dkms/zfs/0.6.3/build/module/zfs/../../module/zfs/arc.c:130:
include/linux/backing-dev.h:120:18: note: previous declaration of 'bdi_setup_and_register' was here
 int __must_check bdi_setup_and_register(struct backing_dev_info *, char *);
                  ^
scripts/Makefile.build:258: recipe for target '/var/lib/dkms/zfs/0.6.3/build/module/zfs/../../module/zfs/arc.o' failed

**Comment by FransUrbo** [comment]
A well known fact - the released 0.6.3 version doesn't compile on kernel 3.17+.

You'd need the 0.6.3-1.2 version. Wherever that can be found, just saw that it's not on http://zfsonlinux.org!

**Comment by colorprint** [comment]
I am using the latest git version - it works fine with kernel 3.19 but gives error above vith 4.0-rc1

**Comment by behlendorf** [comment]
This appears to have been broken by torvalds/linux@b4caecd48005fbed3949dde6c1cb233142fd69e9 which modified the `bdi_setup_and_register()` function.
