### ISSUE TITLE
Build issue with SPL 0.6.4.1

### ISSUE THREAD

**Issue by nvnobelen** [zfsonlinux/zfs#3355]
When building on openSuSE 12.3, I run into a build error:

Making all in module
make[2]: Entering directory `/root/spl-0.6.4.1/module'
make -C /usr/src/linux-3.7.10-1.24-obj/x86_64/default SUBDIRS=`pwd`  O=/usr/src/linux-3.7.10-1.24-obj/x86_64/default CONFIG_SPL=m modules
make[3]: Entering directory `/usr/src/linux-3.7.10-1.24-obj/x86_64/default'
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-proc.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-kmem.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-kmem-cache.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-vmem.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-thread.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-taskq.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-rwlock.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-vnode.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-err.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-kobj.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-generic.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-atomic.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-mutex.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-kstat.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-condvar.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-xdr.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-cred.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-tsd.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-zlib.o
  LD [M]  /root/spl-0.6.4.1/module/spl/spl.o
  CC [M]  /root/spl-0.6.4.1/module/splat/../../module/splat/splat-ctl.o
In file included from /usr/src/linux-3.7.10-1.24/include/linux/fs.h:28:0,
                 from /root/spl-0.6.4.1/module/splat/../../module/splat/splat-ctl.c:50:
/usr/src/linux-3.7.10-1.24/include/linux/percpu-rwsem.h: In function ‘percpu_init_rwsem’:
/usr/src/linux-3.7.10-1.24/include/linux/percpu-rwsem.h:73:20: error: macro "mutex_init" requires 4 arguments, but only 1 given
/usr/src/linux-3.7.10-1.24/include/linux/percpu-rwsem.h:73:2: error: ‘mutex_init’ undeclared (first use in this function)
/usr/src/linux-3.7.10-1.24/include/linux/percpu-rwsem.h:73:2: note: each undeclared identifier is reported only once for each function it appears in
make[7]: *** [/root/spl-0.6.4.1/module/splat/../../module/splat/splat-ctl.o] Error 1
make[6]: *** [/root/spl-0.6.4.1/module/splat] Error 2
make[5]: *** [_module_/root/spl-0.6.4.1/module] Error 2
make[4]: *** [sub-make] Error 2
make[3]: *** [all] Error 2
make[3]: Leaving directory `/usr/src/linux-3.7.10-1.24-obj/x86_64/default'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/root/spl-0.6.4.1/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/spl-0.6.4.1'
make: *** [all] Error 2

The ./configure output:

configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for gawk... gawk
checking metadata... META file
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/x86_64-suse-linux/bin/ld
checking if the linker (/usr/x86_64-suse-linux/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-suse-linux/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking spl author... OpenZFS on Linux
checking spl license... GPL
checking linux distribution... sles
checking default package type... rpm
checking whether rpm is available... yes (4.10.2)
checking whether rpmbuild is available... no
checking whether spec files are available... yes (rpm/generic/*.spec.in)
checking whether dpkg is available... no
checking whether dpkg-buildpackage is available... no
checking whether alien is available... no
checking spl config... all
checking kernel source directory... /usr/src/linux-3.7.10-1.24
checking kernel build directory... /usr/src/linux-3.7.10-1.24-obj/x86_64/default
checking kernel source version... 3.7.10-1.24-default
checking kernel file name for module symbols... Module.symvers
checking whether debugging is enabled... no
checking whether basic kmem accounting is enabled... yes
checking whether detailed kmem tracking is enabled... no
checking whether modules can be built... yes
checking whether atomic types use spinlocks... no
checking whether kernel defines atomic64_t... yes
checking whether old 2-argument shrinker exists... no
checking whether old 3-argument shrinker exists... no
checking whether new 2-argument shrinker exists... yes
checking whether struct ctl_table has ctl_name... no
checking whether PDE_DATA() is available... no
checking whether set_fs_pwd() requires const struct path *... no
checking whether vfs_unlink() wants 2 args... yes
checking whether vfs_rename() wants 4 args... yes
checking whether vfs_fsync() wants 2 args... yes
checking whether truncate_range() inode operation is available... no
checking whether struct fs_struct uses spinlock_t... yes
checking whether kuid_t/kgid_t is available... yes; optional
checking whether __put_task_struct() is available... yes
checking whether rwsem_is_locked() acquires sem->wait_lock... no
checking whether fops->fallocate() exists... yes
checking whether iops->fallocate() exists... no
checking whether fops->fallocate() exists... no
checking whether CONFIG_ZLIB_INFLATE is defined... yes
checking whether CONFIG_ZLIB_DEFLATE is defined... yes
checking whether zlib_deflate_workspacesize() wants 2 args... yes
checking whether struct shrink_control exists... yes
checking whether struct rw_semaphore member wait_lock is raw... yes
checking whether header linux/sched/rt.h exists... no
checking whether vfs_getattr() wants... 3 args
checking whether usleep_range() is available... yes
checking whether struct kmem_cache has allocflags... yes
checking whether wait_on_bit() takes an action... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating man/Makefile
config.status: creating man/man1/Makefile
config.status: creating man/man5/Makefile
config.status: creating lib/Makefile
config.status: creating cmd/Makefile
config.status: creating module/Makefile
config.status: creating module/spl/Makefile
config.status: creating module/splat/Makefile
config.status: creating include/Makefile
config.status: creating include/fs/Makefile
config.status: creating include/linux/Makefile
config.status: creating include/rpc/Makefile
config.status: creating include/sharefs/Makefile
config.status: creating include/sys/Makefile
config.status: creating include/sys/fm/Makefile
config.status: creating include/sys/fs/Makefile
config.status: creating include/sys/sysevent/Makefile
config.status: creating include/util/Makefile
config.status: creating include/vm/Makefile
config.status: creating scripts/Makefile
config.status: creating rpm/Makefile
config.status: creating rpm/redhat/Makefile
config.status: creating rpm/redhat/spl.spec
config.status: creating rpm/redhat/spl-kmod.spec
config.status: creating rpm/redhat/spl-dkms.spec
config.status: creating rpm/generic/Makefile
config.status: creating rpm/generic/spl.spec
config.status: creating rpm/generic/spl-kmod.spec
config.status: creating rpm/generic/spl-dkms.spec
config.status: creating spl.release
config.status: creating spl_config.h
config.status: executing depfiles commands
config.status: executing libtool commands

Full make output:

make  all-recursive
make[1]: Entering directory `/root/spl-0.6.4.1'
Making all in include
make[2]: Entering directory `/root/spl-0.6.4.1/include'
Making all in fs
make[3]: Entering directory `/root/spl-0.6.4.1/include/fs'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/spl-0.6.4.1/include/fs'
Making all in linux
make[3]: Entering directory `/root/spl-0.6.4.1/include/linux'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/spl-0.6.4.1/include/linux'
Making all in rpc
make[3]: Entering directory `/root/spl-0.6.4.1/include/rpc'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/spl-0.6.4.1/include/rpc'
Making all in sharefs
make[3]: Entering directory `/root/spl-0.6.4.1/include/sharefs'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/spl-0.6.4.1/include/sharefs'
Making all in sys
make[3]: Entering directory `/root/spl-0.6.4.1/include/sys'
Making all in fm
make[4]: Entering directory `/root/spl-0.6.4.1/include/sys/fm'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/root/spl-0.6.4.1/include/sys/fm'
Making all in fs
make[4]: Entering directory `/root/spl-0.6.4.1/include/sys/fs'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/root/spl-0.6.4.1/include/sys/fs'
Making all in sysevent
make[4]: Entering directory `/root/spl-0.6.4.1/include/sys/sysevent'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/root/spl-0.6.4.1/include/sys/sysevent'
make[4]: Entering directory `/root/spl-0.6.4.1/include/sys'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/root/spl-0.6.4.1/include/sys'
make[3]: Leaving directory `/root/spl-0.6.4.1/include/sys'
Making all in util
make[3]: Entering directory `/root/spl-0.6.4.1/include/util'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/spl-0.6.4.1/include/util'
Making all in vm
make[3]: Entering directory `/root/spl-0.6.4.1/include/vm'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/spl-0.6.4.1/include/vm'
make[3]: Entering directory `/root/spl-0.6.4.1/include'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/spl-0.6.4.1/include'
make[2]: Leaving directory `/root/spl-0.6.4.1/include'
Making all in rpm
make[2]: Entering directory `/root/spl-0.6.4.1/rpm'
Making all in generic
make[3]: Entering directory `/root/spl-0.6.4.1/rpm/generic'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/spl-0.6.4.1/rpm/generic'
Making all in redhat
make[3]: Entering directory `/root/spl-0.6.4.1/rpm/redhat'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/spl-0.6.4.1/rpm/redhat'
make[3]: Entering directory `/root/spl-0.6.4.1/rpm'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/spl-0.6.4.1/rpm'
make[2]: Leaving directory `/root/spl-0.6.4.1/rpm'
Making all in lib
make[2]: Entering directory `/root/spl-0.6.4.1/lib'
  CC     list.lo
  CCLD   libcommon.la
make[2]: Leaving directory `/root/spl-0.6.4.1/lib'
Making all in cmd
make[2]: Entering directory `/root/spl-0.6.4.1/cmd'
  CC     splat.o
  CCLD   splat
make[2]: Leaving directory `/root/spl-0.6.4.1/cmd'
Making all in man
make[2]: Entering directory `/root/spl-0.6.4.1/man'
Making all in man1
make[3]: Entering directory `/root/spl-0.6.4.1/man/man1'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/spl-0.6.4.1/man/man1'
Making all in man5
make[3]: Entering directory `/root/spl-0.6.4.1/man/man5'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/root/spl-0.6.4.1/man/man5'
make[3]: Entering directory `/root/spl-0.6.4.1/man'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/spl-0.6.4.1/man'
make[2]: Leaving directory `/root/spl-0.6.4.1/man'
Making all in scripts
make[2]: Entering directory `/root/spl-0.6.4.1/scripts'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/spl-0.6.4.1/scripts'
Making all in module
make[2]: Entering directory `/root/spl-0.6.4.1/module'
make -C /usr/src/linux-3.7.10-1.24-obj/x86_64/default SUBDIRS=`pwd`  O=/usr/src/linux-3.7.10-1.24-obj/x86_64/default CONFIG_SPL=m modules
make[3]: Entering directory `/usr/src/linux-3.7.10-1.24-obj/x86_64/default'
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-proc.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-kmem.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-kmem-cache.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-vmem.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-thread.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-taskq.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-rwlock.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-vnode.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-err.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-kobj.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-generic.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-atomic.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-mutex.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-kstat.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-condvar.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-xdr.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-cred.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-tsd.o
  CC [M]  /root/spl-0.6.4.1/module/spl/../../module/spl/spl-zlib.o
  LD [M]  /root/spl-0.6.4.1/module/spl/spl.o
  CC [M]  /root/spl-0.6.4.1/module/splat/../../module/splat/splat-ctl.o
In file included from /usr/src/linux-3.7.10-1.24/include/linux/fs.h:28:0,
                 from /root/spl-0.6.4.1/module/splat/../../module/splat/splat-ctl.c:50:
/usr/src/linux-3.7.10-1.24/include/linux/percpu-rwsem.h: In function ‘percpu_init_rwsem’:
/usr/src/linux-3.7.10-1.24/include/linux/percpu-rwsem.h:73:20: error: macro "mutex_init" requires 4 arguments, but only 1 given
/usr/src/linux-3.7.10-1.24/include/linux/percpu-rwsem.h:73:2: error: ‘mutex_init’ undeclared (first use in this function)
/usr/src/linux-3.7.10-1.24/include/linux/percpu-rwsem.h:73:2: note: each undeclared identifier is reported only once for each function it appears in
make[7]: *** [/root/spl-0.6.4.1/module/splat/../../module/splat/splat-ctl.o] Error 1
make[6]: *** [/root/spl-0.6.4.1/module/splat] Error 2
make[5]: *** [_module_/root/spl-0.6.4.1/module] Error 2
make[4]: *** [sub-make] Error 2
make[3]: *** [all] Error 2
make[3]: Leaving directory `/usr/src/linux-3.7.10-1.24-obj/x86_64/default'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/root/spl-0.6.4.1/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/spl-0.6.4.1'
make: *** [all] Error 2

**Comment by jurt1235** [comment]
Tested build with 0.6.4: Same issue

**Comment by jurt1235** [comment]
Tested build with 0.6.3-1.3: No issues

**Comment by andyeff** [comment]
I have a similar issue trying to install any 0.6.4 package with a RHEL 6.4 system, on kernel 2.6.32-358.23.2.el6.x86_64
Going from 0.6.3-1.3 to 0.6.4.2 in this example:

Updating:
 zfs                              x86_64                       0.6.4.2-1.el6                        zfs                       304 k
Updating for dependencies:
 libnvpair1                       x86_64                       0.6.4.2-1.el6                        zfs                        27 k
 libuutil1                        x86_64                       0.6.4.2-1.el6                        zfs                        32 k
 libzfs2                          x86_64                       0.6.4.2-1.el6                        zfs                       112 k
 libzpool2                        x86_64                       0.6.4.2-1.el6                        zfs                       389 k
 spl                              x86_64                       0.6.4.2-1.el6                        zfs                        24 k
 spl-dkms                         noarch                       0.6.4.2-1.el6                        zfs                       446 k
 zfs-dkms                         noarch                       0.6.4.2-1.el6                        zfs                       1.9 M

Running Transaction
  Updating   : libuutil1-0.6.4.2-1.el6.x86_64                                                                                  1/16
  Updating   : libnvpair1-0.6.4.2-1.el6.x86_64                                                                                 2/16
  Updating   : libzpool2-0.6.4.2-1.el6.x86_64                                                                                  3/16
  Updating   : spl-dkms-0.6.4.2-1.el6.noarch                                                                                   4/16
Non-fatal POSTIN scriptlet failure in rpm package spl-dkms-0.6.4.2-1.el6.noarch
Loading new spl-0.6.4.2 DKMS files...
Building for 2.6.32-358.23.2.el6.x86_64
Building initial module for 2.6.32-358.23.2.el6.x86_64
Error! Bad return status for module build on kernel: 2.6.32-358.23.2.el6.x86_64 (x86_64)
Consult /var/lib/dkms/spl/0.6.4.2/build/make.log for more information.
warning: %post(spl-dkms-0.6.4.2-1.el6.noarch) scriptlet failed, exit status 10
  Updating   : zfs-dkms-0.6.4.2-1.el6.noarch                                                                                   5/16
Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms-0.6.4.2-1.el6.noarch
Loading new zfs-0.6.4.2 DKMS files...
Building for 2.6.32-358.23.2.el6.x86_64
Building initial module for 2.6.32-358.23.2.el6.x86_64
configure: error:
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 2.6.32-358.23.2.el6.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.4.2/build/make.log for more information.
warning: %post(zfs-dkms-0.6.4.2-1.el6.noarch) scriptlet failed, exit status 10

less /var/lib/dkms/spl/0.6.4.2/build/make.log
DKMS make.log for spl-0.6.4.2 for kernel 2.6.32-358.23.2.el6.x86_64 (x86_64)
Sun Jul 19 18:26:52 BST 2015
make  all-recursive
make[1]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build'
Making all in include
make[2]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include'
Making all in fs
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/fs'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/fs'
Making all in linux
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/linux'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/linux'
Making all in rpc
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/rpc'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/rpc'
Making all in sharefs
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/sharefs'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/sharefs'
Making all in sys
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/sys'
Making all in fm
make[4]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/sys/fm'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/sys/fm'
Making all in fs
make[4]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/sys/fs'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/sys/fs'
Making all in sysevent
make[4]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/sys/sysevent'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/sys/sysevent'
make[4]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/sys'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/sys'
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/sys'
Making all in util
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/util'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/util'
Making all in vm
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include/vm'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include/vm'
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/include'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include'
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/include'
Making all in rpm
make[2]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/rpm'
Making all in generic
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/rpm/generic'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/rpm/generic'
Making all in redhat
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/rpm/redhat'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/rpm/redhat'
make[3]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/rpm'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/rpm'
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/rpm'
Making all in module
make[2]: Entering directory `/var/lib/dkms/spl/0.6.4.2/build/module'
make -C /lib/modules/2.6.32-358.23.2.el6.x86_64/build SUBDIRS=`pwd`  CONFIG_SPL=m modules
make[3]: Entering directory `/usr/src/kernels/2.6.32-358.23.2.el6.x86_64'
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-vmem.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-thread.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-taskq.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-rwlock.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-vnode.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-err.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-kobj.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-generic.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-atomic.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-mutex.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-kstat.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-condvar.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-xdr.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-cred.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-tsd.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/../../module/spl/spl-zlib.o
  LD [M]  /var/lib/dkms/spl/0.6.4.2/build/module/spl/spl.o
  CC [M]  /var/lib/dkms/spl/0.6.4.2/build/module/splat/../../module/splat/splat-ctl.o
In file included from include/linux/fs.h:425,
                 from /var/lib/dkms/spl/0.6.4.2/build/module/splat/../../module/splat/splat-ctl.c:50:
include/linux/percpu-rwsem.h:89:20: error: macro "mutex_init" requires 4 arguments, but only 1 given
In file included from include/linux/fs.h:425,
                 from /var/lib/dkms/spl/0.6.4.2/build/module/splat/../../module/splat/splat-ctl.c:50:
include/linux/percpu-rwsem.h: In function 'percpu_init_rwsem':
include/linux/percpu-rwsem.h:89: error: 'mutex_init' undeclared (first use in this function)
include/linux/percpu-rwsem.h:89: error: (Each undeclared identifier is reported only once
include/linux/percpu-rwsem.h:89: error: for each function it appears in.)
make[5]: *** [/var/lib/dkms/spl/0.6.4.2/build/module/splat/../../module/splat/splat-ctl.o] Error 1
make[4]: *** [/var/lib/dkms/spl/0.6.4.2/build/module/splat] Error 2
make[3]: *** [_module_/var/lib/dkms/spl/0.6.4.2/build/module] Error 2
make[3]: Leaving directory `/usr/src/kernels/2.6.32-358.23.2.el6.x86_64'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/dkms/spl/0.6.4.2/build'
make: *** [all] Error 2

The way to resolve this on a test VM was to upgrade to RHEL 6.6 - however this isn't currently an option with the development environment at work.

**Comment by nvnobelen** [comment]
Newer version 0.6.5.3 builds. Closing this one as not being relevant
