### ISSUE TITLE
current_kernel_time vs current_kernel_time64

### ISSUE THREAD

**Issue by mgchristensen** [zfsonlinux/zfs#8451]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 29
Linux Kernel	| 4.20.10-200.fc29.x86_64
Architecture	| o86_64
ZFS Version	| 0.7.12-1
SPL Version	| 0.7.12-1

### Describe the problem you're observing
DKMS has not worked for me since kernel 4.19.10-300.fc29.x86_64, so I have been doing a manual install.  Last few kernel upgrades, spl compiles and installs OK, but zfs does not.
### Describe how to reproduce the problem
./autogen.sh
./configure
make
there are related issues with the 5.0 kernel, but none that I saw with 4.20 kernels

**Comment by mgchristensen** [comment]
the output from make did not appear, so here it is below
```
  CC [M]  /usr/src/zfs-0.7.12/module/zfs/dsl_userhold.o
  CC [M]  /usr/src/zfs-0.7.12/module/zfs/qat_compress.o
  CC [M]  /usr/src/zfs-0.7.12/module/zfs/vdev_raidz_math_sse2.o
  CC [M]  /usr/src/zfs-0.7.12/module/zfs/vdev_raidz_math_ssse3.o
  CC [M]  /usr/src/zfs-0.7.12/module/zfs/vdev_raidz_math_avx2.o
  CC [M]  /usr/src/zfs-0.7.12/module/zfs/vdev_raidz_math_avx512f.o
  CC [M]  /usr/src/zfs-0.7.12/module/zfs/vdev_raidz_math_avx512bw.o
  LD [M]  /usr/src/zfs-0.7.12/module/zfs/zfs.o
  CC [M]  /usr/src/zfs-0.7.12/module/zpios/pios.o
In file included from /usr/src/zfs-0.7.12/include/zpios-internal.h:39,
                 from /usr/src/zfs-0.7.12/module/zpios/pios.c:42:
/usr/src/zfs-0.7.12/include/zpios-ctl.h: In function ‘zpios_timespec_now’:
/usr/src/zfs-0.7.12/include/zpios-ctl.h:186:11: error: implicit declaration of function ‘current_kernel_time’; did you mean ‘current_kernel_time64’? [-Werror=implicit-function-declaration]
  ts_now = current_kernel_time();
           ^~~~~~~~~~~~~~~~~~~
           current_kernel_time64
/usr/src/zfs-0.7.12/include/zpios-ctl.h:186:9: error: incompatible types when assigning to type ‘struct timespec’ from type ‘int’
  ts_now = current_kernel_time();
         ^
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:292: /usr/src/zfs-0.7.12/module/zpios/pios.o] Error 1
make[4]: *** [scripts/Makefile.build:516: /usr/src/zfs-0.7.12/module/zpios] Error 2
make[3]: *** [Makefile:1566: _module_/usr/src/zfs-0.7.12/module] Error 2
make[3]: Leaving directory '/usr/src/kernels/4.20.10-200.fc29.x86_64'
make[2]: *** [Makefile:27: modules] Error 2
make[2]: Leaving directory '/usr/src/zfs-0.7.12/module'
make[1]: *** [Makefile:739: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/zfs-0.7.12'
make: *** [Makefile:608: all] Error 2
```

**Comment by bunder2015** [comment]
same bug, same fix, 0.7.13 and/or 0.8.0 (when it exits RC phase) should fix this.

**Comment by kpande** [comment]
next time check the release notes to see the officially supported kernels for the release you are building.

**Comment by RinCat** [comment]
Same bug happened in zfs 0.7.13 with kernel 5.0.3.
I was successful build in 5.0.0, not sure what changed.
