### ISSUE TITLE
zfs and spl modules from zfsonlinux debian repositories do not build with 4.4.0-0.bpo.1-amd64 kernel from backports

### ISSUE THREAD

**Issue by arachnist** [zfsonlinux/zfs#4476]
```dkms autoinstall -k 4.4.0-0.bpo.1-amd64 -m spl``` and ```dkms autoinstall -k 4.4.0-0.bpo.1-amd64 -m zfs``` fail to compile the zfs modules - the compilation fails with an error:

```
checking whether kmap_atomic wants 1 args... yes
checking whether follow_down_one() is available... yes
checking whether make_request_fn() returns int... no
checking whether make_request_fn() returns void... configure: error: no - Please file a bug report at
                            https://github.com/zfsonlinux/zfs/issues/new

Building module:
cleaning build area....(bad exit status: 2)
make KERNELRELEASE=4.4.0-0.bpo.1-amd64....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.4.0-0.bpo.1-amd64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.2/build/make.log for more information.
```

File `/var/lib/dkms/zfs/0.6.5.2/build/make.log` contains nothing useful:
```
DKMS make.log for zfs-0.6.5.2 for kernel 4.4.0-0.bpo.1-amd64 (x86_64)
Thu Mar 31 02:29:14 CEST 2016
make: *** No targets specified and no makefile found.  Stop.
```

Here's what the `config.log` says (full [config.log here](https://github.com/zfsonlinux/zfs/files/196554/config.log.txt)):
```
configure:20913: checking whether make_request_fn() returns int
configure:20951: cp conftest.c conftest.h build && make modules -C /lib/modules/4.4.0-0.bpo.1-amd64/build EXTRA_CFLAGS=-Werror   M=/var/lib/dkms/zfs/0.6.5.2/build/build 
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
/var/lib/dkms/zfs/0.6.5.2/build/build/conftest.c: In function ‘main’:
/var/lib/dkms/zfs/0.6.5.2/build/build/conftest.c:103:32: error: passing argument 2 of ‘blk_queue_make_request’ from incompatible pointer type [-Werror]
   blk_queue_make_request(NULL, &make_request);
                                ^
In file included from /var/lib/dkms/zfs/0.6.5.2/build/build/conftest.c:92:0:
/usr/src/linux-headers-4.4.0-0.bpo.1-common/include/linux/blkdev.h:962:13: note: expected ‘blk_qc_t (*)(struct request_queue *, struct bio *)’ but argument is of type ‘int (*)(struct request_queue *, struct bio *)’
 extern void blk_queue_make_request(struct request_queue *, make_request_fn *);
             ^
cc1: all warnings being treated as errors
make[3]: *** [/var/lib/dkms/zfs/0.6.5.2/build/build/conftest.o] Error 1
make[2]: *** [_module_/var/lib/dkms/zfs/0.6.5.2/build/build] Error 2
make[1]: *** [sub-make] Error 2
make: *** [all] Error 2
```

```
configure:20977: checking whether make_request_fn() returns void
configure:21015: cp conftest.c conftest.h build && make modules -C /lib/modules/4.4.0-0.bpo.1-amd64/build EXTRA_CFLAGS=-Werror   M=/var/lib/dkms/zfs/0.6.5.2/build/build 
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
/var/lib/dkms/zfs/0.6.5.2/build/build/conftest.c: In function ‘main’:
/var/lib/dkms/zfs/0.6.5.2/build/build/conftest.c:103:33: error: passing argument 2 of ‘blk_queue_make_request’ from incompatible pointer type [-Werror]
    blk_queue_make_request(NULL, &make_request);
                                 ^
In file included from /var/lib/dkms/zfs/0.6.5.2/build/build/conftest.c:92:0:
/usr/src/linux-headers-4.4.0-0.bpo.1-common/include/linux/blkdev.h:962:13: note: expected ‘blk_qc_t (*)(struct request_queue *, struct bio *)’ but argument is of type ‘void (*)(struct request_queue *, struct bio *)’
 extern void blk_queue_make_request(struct request_queue *, make_request_fn *);
             ^
cc1: all warnings being treated as errors
make[3]: *** [/var/lib/dkms/zfs/0.6.5.2/build/build/conftest.o] Error 1
make[2]: *** [_module_/var/lib/dkms/zfs/0.6.5.2/build/build] Error 2
make[1]: *** [sub-make] Error 2
make: *** [all] Error 2
configure:21018: $? = 2
```

```
# dpkg -l '*zfs*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version      Architecture Description
+++-==================-============-============-=================================================
ii  debian-zfs         7~jessie     amd64        Native ZFS filesystem metapackage for Debian.
un  libzfs1            <none>       <none>       (no description available)
ii  libzfs2            0.6.5.2-2    amd64        Native ZFS filesystem library for Linux
un  lzfs               <none>       <none>       (no description available)
un  lzfs-dkms          <none>       <none>       (no description available)
un  zfs                <none>       <none>       (no description available)
un  zfs-auto-snapshot  <none>       <none>       (no description available)
ii  zfs-dkms           0.6.5.2-2    all          Native ZFS filesystem kernel modules for Linux
un  zfs-fuse           <none>       <none>       (no description available)
ii  zfs-initramfs      0.6.5.2-2    amd64        Native ZFS root filesystem capabilities for Linux
un  zfs-modules        <none>       <none>       (no description available)
un  zfs-modules-source <none>       <none>       (no description available)
un  zfsonlinux         <none>       <none>       (no description available)
ii  zfsutils           0.6.5.2-2    amd64        command-line tools to manage ZFS filesystems
```

**Comment by ReimuHakurei** [comment]
Same problem here. When I manually run dkms autoinstall, I get the following more helpful text:

```
[...]
checking whether kmap_atomic wants 1 args... yes
checking whether follow_down_one() is available... yes
checking whether make_request_fn() returns int... no
checking whether make_request_fn() returns void... configure: error: no - Please file a bug report at
                            https://github.com/zfsonlinux/zfs/issues/new

Building module:
cleaning build area....(bad exit status: 2)
make KERNELRELEASE=4.4.0-0.bpo.1-amd64....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.4.0-0.bpo.1-amd64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.2/build/make.log for more information.
```

**Comment by Nilix007** [comment]
The debian repository has not been updated for some time.[0] ZoL 0.6.5.2 is quite old and therefore not compatible with Linux 4.4.[1]

[0]: https://github.com/zfsonlinux/pkg-zfs/issues/181
[1]: https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.2

**Comment by FransUrbo** [comment]
Can someone please verify that **0.6.5.6** (latest released) works with kernel v4.4?

Btw, this belong to the *pkg-zfs* repository, so please create a new ticket there, referencing this and then close this one.

**Comment by ReimuHakurei** [comment]
I compiled the latest version from source and it works fine.

**Comment by arachnist** [comment]
Ok, filled a new issue: zfsonlinux/pkg-zfs#199
