### PR TITLE
3.12 compat, NUMA-aware per-superblock shrinker

### PR DESCRIPTION
**Pull request by dweeezil**
Kernels >= 3.12 have a NUMA-aware superblock shrinker which is used in
ZoL by zfs_sb_prune().  This patch calls the shrinker for each NUMA node
in order that memory be freed in all of them.

### CODE REVIEW

**Comment by dweeezil** [comment]
This is marginally related to #3308.  Over time, more and more of the memory management has gained NUMA-awareness.  The initial patch only calls the shrinker for each node used by the dentry cache.  In my testing, I also did the same for the inode cache but it seems that calling the shrinker for only the nodes used by the dentry cache has the side-effect of un-pinning old inodes as well.

This patch should work on all kernels >= 3.12.  There are, however, several commits in the kernel between the addition of the split shrinker scheme (torvalds/linux@24f7c6b9) and the conversion of the superblock shrinker to NUMA-awareness (torvalds/linux@1d3d4437) on whch it will not compile.

The only bare-metal NUMA system on which I can run tests has so much RAM that I can't easily (in a reasonable amount of time) get any memory used in more than 1 NUMA node (limiting with ```mem=``` only gives the first node memory).  My testing was performed on a KVM vm guest simulating a 2-node NUMA system with 2 cores per node.  I added some instrumentation to help me gain confidence it was working:
```
[  665.467647] zfs_sb_prune: 105125 dentries on node 0
[  665.469712] zfs_sb_prune: 92191 dentries on node 1
```

**Comment by angstymeat** [comment]
I think this may have fixed my problems! My memory usage looks very different in my graphs. The system continuously has free memory, and my rsyncs are running at full speed.

I will let it run for a day or two to see how it does. I have thought it was fixed before, but had problems after a day or two.

**Comment by angstymeat** [comment]
Ok, I've run this twice in a row, and memory and speed look really good. I hadn't noticed how my memory graphs had been flat the last 6 months, but now I'm seeing lots of peaks as memory usage is changing during the backups.

I really think that has fixed it.

**Comment by sempervictus** [comment]
This doesnt compile on kernel 4.0.4:
```
 CC [M]  /var/lib/dkms/zfs/0.6.4/build/module/zfs/../../module/zfs/zfs_vfsops.o
In file included from include/linux/mmzone.h:16:0,
                 from include/linux/gfp.h:5,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/src/spl-0.6.4/include/sys/sysmacros.h:28,
                 from /usr/src/spl-0.6.4/include/sys/types.h:29,
                 from /var/lib/dkms/zfs/0.6.4/build/module/zfs/../../module/zfs/zfs_vfsops.c:28:
/var/lib/dkms/zfs/0.6.4/build/module/zfs/../../module/zfs/zfs_vfsops.c: In function ‘zfs_sb_prune’:
/var/lib/dkms/zfs/0.6.4/build/module/zfs/../../module/zfs/zfs_vfsops.c:1100:42: error: ‘struct list_lru’ has no member named ‘active_nodes’
  for_each_node_mask(nid, sb->s_dentry_lru.active_nodes) {
                                          ^
include/linux/nodemask.h:250:40: note: in definition of macro ‘first_node’
 #define first_node(src) __first_node(&(src))
                                        ^
/var/lib/dkms/zfs/0.6.4/build/module/zfs/../../module/zfs/zfs_vfsops.c:1100:2: note: in expansion of macro ‘for_each_node_mask’
  for_each_node_mask(nid, sb->s_dentry_lru.active_nodes) {
  ^
/var/lib/dkms/zfs/0.6.4/build/module/zfs/../../module/zfs/zfs_vfsops.c:1100:42: error: ‘struct list_lru’ has no member named ‘active_nodes’
  for_each_node_mask(nid, sb->s_dentry_lru.active_nodes) {
                                          ^
include/linux/nodemask.h:256:46: note: in definition of macro ‘next_node’
 #define next_node(n, src) __next_node((n), &(src))
                                              ^
/var/lib/dkms/zfs/0.6.4/build/module/zfs/../../module/zfs/zfs_vfsops.c:1100:2: note: in expansion of macro ‘for_each_node_mask’
  for_each_node_mask(nid, sb->s_dentry_lru.active_nodes) {
  ^
make[5]: *** [/var/lib/dkms/zfs/0.6.4/build/module/zfs/../../module/zfs/zfs_vfsops.o] Error 1
```
Git blame says:
```
9871e880 module/zfs/zfs_vfsops.c         (Tim Chase          2015-06-14 11:19:40 -0500 1100) 	for_each_node_mask(nid, sb->s_dentry_lru.active_nodes) {
```
So i figure we might have a problem here.

**Comment by dweeezil** [comment]
@sempervictus This has been fixed in subsequent re-pushes of the branch (320625e).  I'll note, however, that it won't compile with the latest 4.1-rc kernels without #3421, which you can cleanly cherry-pick if necessary.

**Comment by behlendorf** [comment]
@dweeezil this explains quite a lot.  I'd wondered why people were hitting this issue even though they have the per-filesystem shrinkers.  Nice find and fix.  I have a patch similar in spirit for old kernels I'll push for review.

In regards to the inode being dropped right away when the dentry is free'd this is something which we did intentionally.  The `drop_inode` hook is setup such that when the last reference in dropped the inode is immediately removed from the cache.  This was done because it helps free up meta data faster and it's proven problematic to force the inode cache to be dropped for various kernel version.  As long as the dnode block backing the the inode is cached in the ARC its cheap to recreate.  This behavior could be changed.

@angstymeat thanks for the quick feedback on this.

**Comment by angstymeat** [comment]
@behlendorf Not a problem!

@dweeezil It still looks good. Backup ran fine last night, and that's after I removed the ```nr_cpus``` and set ```zfs_arc_meta_prune``` back to its default of 10000. All of my settings should be at default now.

This issue was keeping me from deploying 0.6.4 on our other systems, but now that it's been figured out I can start updating some of our machines.

**Comment by dweeezil** [comment]
@behlendorf Thanks for the pointer to the ```drop_inode``` callback.  That makes perfect sense.

@angstymeat Thanks for the feedback.  This was one of many issues I left hanging while trying to get #3115 pushed through (which was a much longer process than I had expected).

**Comment by dweeezil** [comment]
@angstymeat I forgot to ask:  Could you please make sure to try the latest commit (320625e).  It should work just the same for you but it uses a different method for iterating over the nodes which is compatible with newer kernels.

**Comment by dweeezil** [comment]
@behlendorf I fixed the ```*objects``` calculation; initialized to zero and accumulate as it goes.

**Comment by dweeezil** [comment]
Pushed d65028a which uses the proper on-line NUMA node iterator and adds an autoconf check for NUMA-aware shrink_control and a run-time check for NUMA-aware superblock shrinker which will save a bit of processing on non-NUMA systems running NUMA-supporting kernels.

**Comment by angstymeat** [comment]
@dweeezil Testing the lastest push right now.

**Comment by behlendorf** [comment]
I like it.  This is definitely something we'll want to pull in to the -release branch once it's merged to master.

**Comment by angstymeat** [comment]
@dweeezil It still appears to be working. It just blew right through my backup routine.

**Comment by behlendorf** [comment]
LGTM merged.
