### ISSUE TITLE
Can't compile with 4.4.0 kernel due to "implicit declaration of function ‘vn_remove’"

### ISSUE THREAD

**Issue by aarononeal** [zfsonlinux/zfs#7187]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04.3 LTS (Xenial Xerus)
Linux Kernel                 | 4.4.0-1050-aws
Architecture                 | x86_64
ZFS Version                  | master
SPL Version                  | master

### Describe the problem you're observing

The `zfs` repo fails to compile.

```
  CC [M]  /home/ubuntu/dev/zfs/module/zfs/spa_config.o
/home/ubuntu/dev/zfs/module/zfs/spa_config.c: In function ‘spa_config_write’:
/home/ubuntu/dev/zfs/module/zfs/spa_config.c:164:9: error: implicit declaration of function ‘vn_remove’ [-Werror=implicit-function-declaration]
   err = vn_remove(dp->scd_path, UIO_SYSSPACE, RMFILE);
```

The pre-built kernel module that comes with the kernel appears to also have this same symbol issue.

```
depmod: WARNING: /lib/modules/4.4.0-1050-aws/kernel/zfs/zfs/zfs.ko needs unknown symbol vn_remove
```

### Describe how to reproduce the problem

1. Install Ubuntu
2. Compile master from github

**Comment by DeHackEd** [comment]
This was changed recently in SPL. Make sure you update and recompile both SPL and ZFS, including re-running autogen.sh

See zfsonlinux/spl@8be368899918e2786f2fed84dc746de1894b06c1

**Comment by aarononeal** [comment]
Both my SPL and ZFS repos say they're up to date on the master branch. It looks like `vn_remove` was removed from SPL and that's what's breaking the ZFS compile which still references it.

**Comment by aarononeal** [comment]
After inspecting the file I discovered that the local repo on this machine wasn't updating. Pulling down a new copy now. Sorry for the noise and thanks for the pointer.
