### ISSUE TITLE
compile error with zfs 0.8.3 and kernel 5.6rc1

### ISSUE THREAD

**Issue by freswa** [zfsonlinux/zfs#10001]
Distribution Name | Archlinux
Distribution Version | current
Linux Kernel | 5.6rc1
Architecture | amd64
ZFS Version | 0.8.3

Make log (shortened):
```
DKMS make.log for zfs-0.8.3 for kernel 5.6.0-rc1-1-mainline (x86_64)
2020-02-13T16:31:04 CET
make: Entering directory '/var/lib/dkms/zfs/0.8.3/build/module'
list='icp lua'; for targetdir in $list; do \
	make -C $targetdir; \
done
make[1]: Entering directory '/var/lib/dkms/zfs/0.8.3/build/module/icp'
mkdir -p api core spi io os algs algs/aes algs/edonr algs/modes algs/sha1 algs/sha2 algs/skein asm-x86_64 asm-x86_64/aes asm-x86_64/modes asm-x86_64/sha1 asm-x86_64/sha2 asm-i386 asm-generic
make[1]: Leaving directory '/var/lib/dkms/zfs/0.8.3/build/module/icp'
make[1]: Entering directory '/var/lib/dkms/zfs/0.8.3/build/module/lua'
mkdir -p setjmp
make[1]: Leaving directory '/var/lib/dkms/zfs/0.8.3/build/module/lua'
make -C /usr/lib/modules/5.6.0-rc1-1-mainline/build M=`pwd`  CONFIG_ZFS=m modules
make[1]: Entering directory '/usr/lib/modules/5.6.0-rc1-1-mainline/build'
<compilation messages without errors or warnings>
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/lua/lfunc.o
/var/lib/dkms/zfs/0.8.3/build/module/spl/spl-kstat.c: In function ‘kstat_proc_entry_install’:
/var/lib/dkms/zfs/0.8.3/build/module/spl/spl-kstat.c:693:24: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  693 |      module->ksm_proc, file_ops, data);
      |                        ^~~~~~~~
      |                        |
      |                        const struct file_operations *
In file included from /var/lib/dkms/zfs/0.8.3/build/include/spl/sys/proc.h:28,
                 from /var/lib/dkms/zfs/0.8.3/build/include/spl/sys/kstat.h:33,
                 from /var/lib/dkms/zfs/0.8.3/build/module/spl/spl-kstat.c:28:
./include/linux/proc_fs.h:59:31: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
   59 | extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
      |                               ^~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/spl/spl-procfs-list.o
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/zcommon/zfs_fletcher_intel.o
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/lua/lgc.o
/var/lib/dkms/zfs/0.8.3/build/module/spl/spl-proc.c: In function ‘spl_proc_init’:
/var/lib/dkms/zfs/0.8.3/build/module/spl/spl-proc.c:741:6: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  741 |      &proc_taskq_all_operations, NULL);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |      |
      |      struct file_operations *
In file included from /var/lib/dkms/zfs/0.8.3/build/include/spl/sys/proc.h:28,
                 from /var/lib/dkms/zfs/0.8.3/build/include/spl/sys/kstat.h:33,
                 from /var/lib/dkms/zfs/0.8.3/build/module/spl/spl-proc.c:28:
./include/linux/proc_fs.h:59:31: note: expected ‘const struct proc_ops *’ but argument is of type ‘struct file_operations *’
   59 | extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
      |                               ^~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.3/build/module/spl/spl-proc.c:748:6: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  748 |      &proc_taskq_operations, NULL);
      |      ^~~~~~~~~~~~~~~~~~~~~~
      |      |
      |      struct file_operations *
In file included from /var/lib/dkms/zfs/0.8.3/build/include/spl/sys/proc.h:28,
                 from /var/lib/dkms/zfs/0.8.3/build/include/spl/sys/kstat.h:33,
                 from /var/lib/dkms/zfs/0.8.3/build/module/spl/spl-proc.c:28:
./include/linux/proc_fs.h:59:31: note: expected ‘const struct proc_ops *’ but argument is of type ‘struct file_operations *’
   59 | extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
      |                               ^~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.3/build/module/spl/spl-proc.c:761:6: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  761 |      &proc_slab_operations, NULL);
      |      ^~~~~~~~~~~~~~~~~~~~~
      |      |
      |      struct file_operations *
In file included from /var/lib/dkms/zfs/0.8.3/build/include/spl/sys/proc.h:28,
                 from /var/lib/dkms/zfs/0.8.3/build/include/spl/sys/kstat.h:33,
                 from /var/lib/dkms/zfs/0.8.3/build/module/spl/spl-proc.c:28:
./include/linux/proc_fs.h:59:31: note: expected ‘const struct proc_ops *’ but argument is of type ‘struct file_operations *’
   59 | extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
      |                               ^~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/zcommon/zfs_fletcher_sse.o
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/zcommon/zfs_fletcher_avx512.o
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:267: /var/lib/dkms/zfs/0.8.3/build/module/spl/spl-kstat.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/lua/llex.o
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:267: /var/lib/dkms/zfs/0.8.3/build/module/spl/spl-proc.o] Error 1
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/lua/lmem.o
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/lua/lobject.o
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/lua/lopcodes.o
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/icp/api/kcf_mac.o
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/icp/api/kcf_miscapi.o
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/icp/api/kcf_ctxops.o
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/icp/core/kcf_callprov.o
make[2]: *** [scripts/Makefile.build:505: /var/lib/dkms/zfs/0.8.3/build/module/spl] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/lua/lparser.o
<compilation messages without errors or warnings>
  AS [M]  /var/lib/dkms/zfs/0.8.3/build/module/icp/asm-x86_64/sha2/sha512_impl.o
/var/lib/dkms/zfs/0.8.3/build/module/icp/asm-x86_64/sha2/sha256_impl.o: warning: objtool: SHA256TransformBlocks()+0x19: unsupported stack pointer realignment
/var/lib/dkms/zfs/0.8.3/build/module/icp/asm-x86_64/sha1/sha1-x86_64.o: warning: objtool: sha1_block_data_order()+0x11: unsupported stack pointer realignment
/var/lib/dkms/zfs/0.8.3/build/module/icp/asm-x86_64/sha2/sha512_impl.o: warning: objtool: SHA512TransformBlocks()+0x1c: unsupported stack pointer realignment
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/zfs/metaslab.o
<compilation messages without errors or warnings>
  CC [M]  /var/lib/dkms/zfs/0.8.3/build/module/zfs/zpl_super.o
In file included from /var/lib/dkms/zfs/0.8.3/build/include/sys/policy.h:36,
                 from /var/lib/dkms/zfs/0.8.3/build/module/zfs/zfs_vnops.c:59:
/var/lib/dkms/zfs/0.8.3/build/module/zfs/zfs_vnops.c: In function ‘zfs_setattr’:
/var/lib/dkms/zfs/0.8.3/build/include/sys/zpl.h:195:44: error: implicit declaration of function ‘timespec64_trunc’; did you mean ‘timespec64_to_ns’? [-Werror=implicit-function-declaration]
  195 | #define zpl_inode_timespec_trunc(ts, gran) timespec64_trunc(ts, gran)
      |                                            ^~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.3/build/module/zfs/zfs_vnops.c:3418:23: note: in expansion of macro ‘zpl_inode_timespec_trunc’
 3418 |   ZTOI(zp)->i_mtime = zpl_inode_timespec_trunc(vap->va_mtime,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.3/build/include/sys/zpl.h:195:44: error: incompatible types when assigning to type ‘struct timespec64’ from type ‘int’
  195 | #define zpl_inode_timespec_trunc(ts, gran) timespec64_trunc(ts, gran)
      |                                            ^~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.3/build/module/zfs/zfs_vnops.c:3418:23: note: in expansion of macro ‘zpl_inode_timespec_trunc’
 3418 |   ZTOI(zp)->i_mtime = zpl_inode_timespec_trunc(vap->va_mtime,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.3/build/include/sys/zpl.h:195:44: error: incompatible types when assigning to type ‘struct timespec64’ from type ‘int’
  195 | #define zpl_inode_timespec_trunc(ts, gran) timespec64_trunc(ts, gran)
      |                                            ^~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.3/build/module/zfs/zfs_vnops.c:3427:23: note: in expansion of macro ‘zpl_inode_timespec_trunc’
 3427 |   ZTOI(zp)->i_ctime = zpl_inode_timespec_trunc(vap->va_ctime,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:268: /var/lib/dkms/zfs/0.8.3/build/module/zfs/zfs_vnops.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /var/lib/dkms/zfs/0.8.3/build/include/sys/zfs_vnops.h:34,
                 from /var/lib/dkms/zfs/0.8.3/build/module/zfs/zpl_inode.c:29:
/var/lib/dkms/zfs/0.8.3/build/module/zfs/zpl_inode.c: In function ‘zpl_setattr’:
/var/lib/dkms/zfs/0.8.3/build/include/sys/zpl.h:195:44: error: implicit declaration of function ‘timespec64_trunc’; did you mean ‘timespec64_to_ns’? [-Werror=implicit-function-declaration]
  195 | #define zpl_inode_timespec_trunc(ts, gran) timespec64_trunc(ts, gran)
      |                                            ^~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.3/build/module/zfs/zpl_inode.c:394:17: note: in expansion of macro ‘zpl_inode_timespec_trunc’
  394 |   ip->i_atime = zpl_inode_timespec_trunc(ia->ia_atime,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.3/build/include/sys/zpl.h:195:44: error: incompatible types when assigning to type ‘struct timespec64’ from type ‘int’
  195 | #define zpl_inode_timespec_trunc(ts, gran) timespec64_trunc(ts, gran)
      |                                            ^~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/0.8.3/build/module/zfs/zpl_inode.c:394:17: note: in expansion of macro ‘zpl_inode_timespec_trunc’
  394 |   ip->i_atime = zpl_inode_timespec_trunc(ia->ia_atime,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:267: /var/lib/dkms/zfs/0.8.3/build/module/zfs/zpl_inode.o] Error 1
make[2]: *** [scripts/Makefile.build:505: /var/lib/dkms/zfs/0.8.3/build/module/zfs] Error 2
make[1]: *** [Makefile:1681: /var/lib/dkms/zfs/0.8.3/build/module] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.6.0-rc1-1-mainline/build'
make: *** [Makefile:30: modules] Error 2
make: Leaving directory '/var/lib/dkms/zfs/0.8.3/build/module'

**Comment by satmandu** [comment]
I modified the patches at https://github.com/zfsonlinux/zfs/pull/9961 for the zfs-0.8-release branch to ubuntu's zfs-dkms_0.8.3-1ubuntu3 package and have been able to get my zpools to work using the ubuntu 5.6.0-050600rc1-generic mainline build.

Here's the patch, which I have only tested with kernel 5.5 on arm64 and kernel 5.5 and kernel 5.6rc1 on amd64: https://paste.ubuntu.com/p/wsS9GFHjyv/

```
diff -Npur a/META b/META
--- a/META	2020-02-06 03:51:22.000000000 -0500
+++ b/META	2020-02-12 19:22:39.522594648 -0500
@@ -6,5 +6,5 @@ Release:      1ubuntu3
 Release-Tags:  relext
 License:       CDDL
 Author:        OpenZFS on Linux
-Linux-Maximum: 5.4
+Linux-Maximum: 5.6
 Linux-Minimum: 2.6.32
diff -Npur a/config/kernel-inode-times.m4 b/config/kernel-inode-times.m4
--- a/config/kernel-inode-times.m4	2020-01-22 16:49:01.000000000 -0500
+++ b/config/kernel-inode-times.m4	2020-02-12 19:02:10.209618383 -0500
@@ -1,8 +1,22 @@
-dnl #
-dnl # 4.18 API change
-dnl # i_atime, i_mtime, and i_ctime changed from timespec to timespec64.
-dnl #
 AC_DEFUN([ZFS_AC_KERNEL_SRC_INODE_TIMES], [
+
+	dnl #
+	dnl # 5.6 API change
+	dnl # timespec64_trunc() replaced by timestamp_truncate() interface.
+	dnl #
+	ZFS_LINUX_TEST_SRC([timestamp_truncate], [
+		#include <linux/fs.h>
+	],[
+		struct timespec64 ts;
+		struct inode ip;
+
+		ts = timestamp_truncate(ts, &ip);
+	])
+
+	dnl #
+	dnl # 4.18 API change
+	dnl # i_atime, i_mtime, and i_ctime changed from timespec to timespec64.
+	dnl #
 	ZFS_LINUX_TEST_SRC([inode_times], [
 		#include <linux/fs.h>
 	],[
@@ -15,6 +29,15 @@ AC_DEFUN([ZFS_AC_KERNEL_SRC_INODE_TIMES]
 ])
 
 AC_DEFUN([ZFS_AC_KERNEL_INODE_TIMES], [
+	AC_MSG_CHECKING([whether timestamp_truncate() exists])
+	ZFS_LINUX_TEST_RESULT([timestamp_truncate], [
+		AC_MSG_RESULT(yes)
+		AC_DEFINE(HAVE_INODE_TIMESTAMP_TRUNCATE, 1,
+		    [timestamp_truncate() exists])
+	],[
+		AC_MSG_RESULT(no)
+	])
+
 	AC_MSG_CHECKING([whether inode->i_*time's are timespec64])
 	ZFS_LINUX_TEST_RESULT([inode_times], [
 		AC_MSG_RESULT(no)
diff -Npur a/config/kernel-proc-operations.m4 b/config/kernel-proc-operations.m4
--- a/config/kernel-proc-operations.m4	1969-12-31 19:00:00.000000000 -0500
+++ b/config/kernel-proc-operations.m4	2020-02-12 23:00:17.797516225 -0500
@@ -0,0 +1,41 @@
+dnl #
+dnl # 5.6 API Change
+dnl # The proc_ops structure was introduced to replace the use of
+dnl # of the file_operations structure when registering proc handlers.
+dnl #
+AC_DEFUN([ZFS_AC_KERNEL_SRC_PROC_OPERATIONS], [
+	ZFS_LINUX_TEST_SRC([proc_ops_struct], [
+		#include <linux/proc_fs.h>
+
+		int test_open(struct inode *ip, struct file *fp) { return 0; }
+		ssize_t test_read(struct file *fp, char __user *ptr,
+		    size_t size, loff_t *offp) { return 0; }
+		ssize_t test_write(struct file *fp, const char __user *ptr,
+		    size_t size, loff_t *offp) { return 0; }
+		loff_t test_lseek(struct file *fp, loff_t off, int flag)
+		    { return 0; }
+		int test_release(struct inode *ip, struct file *fp)
+		    { return 0; }
+
+		const struct proc_ops test_ops __attribute__ ((unused)) = {
+			.proc_open      = test_open,
+			.proc_read      = test_read,
+			.proc_write	= test_write,
+			.proc_lseek     = test_lseek,
+			.proc_release   = test_release,
+		};
+	], [
+		struct proc_dir_entry *entry __attribute__ ((unused)) =
+		    proc_create_data("test", 0444, NULL, &test_ops, NULL);
+	])
+])
+
+AC_DEFUN([ZFS_AC_KERNEL_PROC_OPERATIONS], [
+	AC_MSG_CHECKING([whether proc_ops structure exists])
+	ZFS_LINUX_TEST_RESULT([proc_ops_struct], [
+		AC_MSG_RESULT(yes)
+		AC_DEFINE(HAVE_PROC_OPS_STRUCT, 1, [proc_ops structure exists])
+	], [
+		AC_MSG_RESULT(no)
+	])
+])
diff -Npur a/config/kernel.m4 b/config/kernel.m4
--- a/config/kernel.m4	2020-01-22 16:49:04.000000000 -0500
+++ b/config/kernel.m4	2020-02-12 19:01:50.034206248 -0500
@@ -54,6 +54,7 @@ AC_DEFUN([ZFS_AC_KERNEL_TEST_SRC], [
 	ZFS_AC_KERNEL_SRC_CURRENT_BIO_TAIL
 	ZFS_AC_KERNEL_SRC_SUPER_USER_NS
 	ZFS_AC_KERNEL_SRC_SUBMIT_BIO
+	ZFS_AC_KERNEL_SRC_PROC_OPERATIONS
 	ZFS_AC_KERNEL_SRC_BLOCK_DEVICE_OPERATIONS
 	ZFS_AC_KERNEL_SRC_BLKDEV_GET_BY_PATH
 	ZFS_AC_KERNEL_SRC_BLKDEV_REREAD_PART
@@ -169,6 +170,7 @@ AC_DEFUN([ZFS_AC_KERNEL_TEST_RESULT], [
 	ZFS_AC_KERNEL_TIMER_SETUP
 	ZFS_AC_KERNEL_CURRENT_BIO_TAIL
 	ZFS_AC_KERNEL_SUPER_USER_NS
+	ZFS_AC_KERNEL_PROC_OPERATIONS
 	ZFS_AC_KERNEL_SUBMIT_BIO
 	ZFS_AC_KERNEL_BLOCK_DEVICE_OPERATIONS
 	ZFS_AC_KERNEL_BLKDEV_GET_BY_PATH
diff -Npur a/include/spl/sys/kstat.h b/include/spl/sys/kstat.h
--- a/include/spl/sys/kstat.h	2020-01-13 17:17:11.000000000 -0500
+++ b/include/spl/sys/kstat.h	2020-02-12 19:06:10.482633626 -0500
@@ -152,6 +152,12 @@ typedef struct kstat_named_s {
 #define	KSTAT_NAMED_STR_PTR(knptr) ((knptr)->value.string.addr.ptr)
 #define	KSTAT_NAMED_STR_BUFLEN(knptr) ((knptr)->value.string.len)
 
+#ifdef HAVE_PROC_OPS_STRUCT
+typedef struct proc_ops kstat_proc_op_t;
+#else
+typedef struct file_operations kstat_proc_op_t;
+#endif
+
 typedef struct kstat_intr {
 	uint_t intrs[KSTAT_NUM_INTRS];
 } kstat_intr_t;
@@ -197,7 +203,7 @@ extern void kstat_proc_entry_init(kstat_
     const char *module, const char *name);
 extern void kstat_proc_entry_delete(kstat_proc_entry_t *kpep);
 extern void kstat_proc_entry_install(kstat_proc_entry_t *kpep, mode_t mode,
-    const struct file_operations *file_ops, void *data);
+    const kstat_proc_op_t *file_ops, void *data);
 
 extern void __kstat_install(kstat_t *ksp);
 extern void __kstat_delete(kstat_t *ksp);
diff -Npur a/include/sys/zpl.h b/include/sys/zpl.h
--- a/include/sys/zpl.h	2020-01-13 17:17:11.000000000 -0500
+++ b/include/sys/zpl.h	2020-02-12 19:08:50.536237304 -0500
@@ -188,13 +188,14 @@ zpl_dir_emit_dots(struct file *file, zpl
 }
 #endif /* HAVE_VFS_ITERATE */
 
-/*
- * Linux 4.18, inode times converted from timespec to timespec64.
- */
-#if defined(HAVE_INODE_TIMESPEC64_TIMES)
-#define	zpl_inode_timespec_trunc(ts, gran)	timespec64_trunc(ts, gran)
+#if defined(HAVE_INODE_TIMESTAMP_TRUNCATE)
+#define	zpl_inode_timestamp_truncate(ts, ip)	timestamp_truncate(ts, ip)
+#elif defined(HAVE_INODE_TIMESPEC64_TIMES)
+#define	zpl_inode_timestamp_truncate(ts, ip)	\
+	timespec64_trunc(ts, (ip)->i_sb->s_time_gran)
 #else
-#define	zpl_inode_timespec_trunc(ts, gran)	timespec_trunc(ts, gran)
+#define	zpl_inode_timestamp_truncate(ts, ip)	\
+	timespec_trunc(ts, (ip)->i_sb->s_time_gran)
 #endif
 
 #endif	/* _SYS_ZPL_H */
diff -Npur a/module/spl/spl-kstat.c b/module/spl/spl-kstat.c
--- a/module/spl/spl-kstat.c	2020-02-06 03:51:22.000000000 -0500
+++ b/module/spl/spl-kstat.c	2020-02-12 19:10:49.254149144 -0500
@@ -507,12 +507,20 @@ proc_kstat_write(struct file *filp, cons
 	return (len);
 }
 
-static struct file_operations proc_kstat_operations = {
+static const kstat_proc_op_t proc_kstat_operations = {
+#ifdef HAVE_PROC_OPS_STRUCT
+	.proc_open	= proc_kstat_open,
+	.proc_write	= proc_kstat_write,
+	.proc_read	= seq_read,
+	.proc_lseek	= seq_lseek,
+	.proc_release	= seq_release,
+#else
 	.open		= proc_kstat_open,
 	.write		= proc_kstat_write,
 	.read		= seq_read,
 	.llseek		= seq_lseek,
 	.release	= seq_release,
+#endif
 };
 
 void
@@ -656,7 +664,7 @@ kstat_detect_collision(kstat_proc_entry_
  */
 void
 kstat_proc_entry_install(kstat_proc_entry_t *kpep, mode_t mode,
-    const struct file_operations *file_ops, void *data)
+    const kstat_proc_op_t *proc_ops, void *data)
 {
 	kstat_module_t *module;
 	kstat_proc_entry_t *tmp = NULL;
@@ -690,7 +698,7 @@ kstat_proc_entry_install(kstat_proc_entr
 
 	kpep->kpe_owner = module;
 	kpep->kpe_proc = proc_create_data(kpep->kpe_name, mode,
-	    module->ksm_proc, file_ops, data);
+	    module->ksm_proc, proc_ops, data);
 	if (kpep->kpe_proc == NULL) {
 		list_del_init(&kpep->kpe_list);
 		if (list_empty(&module->ksm_kstat_list))
diff -Npur a/module/spl/spl-proc.c b/module/spl/spl-proc.c
--- a/module/spl/spl-proc.c	2020-02-06 03:51:22.000000000 -0500
+++ b/module/spl/spl-proc.c	2020-02-12 19:12:31.268190180 -0500
@@ -532,11 +532,18 @@ proc_slab_open(struct inode *inode, stru
 	return (seq_open(filp, &slab_seq_ops));
 }
 
-static struct file_operations proc_slab_operations = {
-	.open	   = proc_slab_open,
-	.read	   = seq_read,
-	.llseek	 = seq_lseek,
+static const kstat_proc_op_t proc_slab_operations = {
+#ifdef HAVE_PROC_OPS_STRUCT
+	.proc_open	= proc_slab_open,
+	.proc_read	= seq_read,
+	.proc_lseek	= seq_lseek,
+	.proc_release	= seq_release,
+#else
+	.open		= proc_slab_open,
+	.read		= seq_read,
+	.llseek		= seq_lseek,
 	.release	= seq_release,
+#endif
 };
 
 static void
@@ -571,18 +578,32 @@ proc_taskq_open(struct inode *inode, str
 	return (seq_open(filp, &taskq_seq_ops));
 }
 
-static struct file_operations proc_taskq_all_operations = {
+static const kstat_proc_op_t proc_taskq_all_operations = {
+#ifdef HAVE_PROC_OPS_STRUCT
+	.proc_open	= proc_taskq_all_open,
+	.proc_read	= seq_read,
+	.proc_lseek	= seq_lseek,
+	.proc_release	= seq_release,
+#else
 	.open		= proc_taskq_all_open,
 	.read		= seq_read,
 	.llseek		= seq_lseek,
 	.release	= seq_release,
+#endif
 };
 
-static struct file_operations proc_taskq_operations = {
+static const kstat_proc_op_t proc_taskq_operations = {
+#ifdef HAVE_PROC_OPS_STRUCT
+	.proc_open	= proc_taskq_open,
+	.proc_read	= seq_read,
+	.proc_lseek	= seq_lseek,
+	.proc_release	= seq_release,
+#else
 	.open		= proc_taskq_open,
 	.read		= seq_read,
 	.llseek		= seq_lseek,
 	.release	= seq_release,
+#endif
 };
 
 static struct ctl_table spl_kmem_table[] = {
diff -Npur a/module/spl/spl-procfs-list.c b/module/spl/spl-procfs-list.c
--- a/module/spl/spl-procfs-list.c	2020-02-06 03:51:22.000000000 -0500
+++ b/module/spl/spl-procfs-list.c	2020-02-12 19:13:16.315284523 -0500
@@ -185,13 +185,20 @@ procfs_list_write(struct file *filp, con
 	return (len);
 }
 
-static struct file_operations procfs_list_operations = {
-	.owner		= THIS_MODULE,
+static const kstat_proc_op_t procfs_list_operations = {
+#ifdef HAVE_PROC_OPS_STRUCT
+	.proc_open	= procfs_list_open,
+	.proc_write	= procfs_list_write,
+	.proc_read	= seq_read,
+	.proc_lseek	= seq_lseek,
+	.proc_release	= seq_release_private,
+#else
 	.open		= procfs_list_open,
 	.write		= procfs_list_write,
 	.read		= seq_read,
 	.llseek		= seq_lseek,
 	.release	= seq_release_private,
+#endif
 };
 
 /*
diff -Npur a/module/zfs/zfs_vnops.c b/module/zfs/zfs_vnops.c
--- a/module/zfs/zfs_vnops.c	2020-02-06 03:51:22.000000000 -0500
+++ b/module/zfs/zfs_vnops.c	2020-02-12 19:14:40.337538104 -0500
@@ -3415,8 +3415,8 @@ top:
 
 	if (mask & (ATTR_MTIME | ATTR_SIZE)) {
 		ZFS_TIME_ENCODE(&vap->va_mtime, mtime);
-		ZTOI(zp)->i_mtime = zpl_inode_timespec_trunc(vap->va_mtime,
-		    ZTOI(zp)->i_sb->s_time_gran);
+		ZTOI(zp)->i_mtime = zpl_inode_timestamp_truncate(
+		    vap->va_mtime, ZTOI(zp));
 
 		SA_ADD_BULK_ATTR(bulk, count, SA_ZPL_MTIME(zfsvfs), NULL,
 		    mtime, sizeof (mtime));
@@ -3424,8 +3424,8 @@ top:
 
 	if (mask & (ATTR_CTIME | ATTR_SIZE)) {
 		ZFS_TIME_ENCODE(&vap->va_ctime, ctime);
-		ZTOI(zp)->i_ctime = zpl_inode_timespec_trunc(vap->va_ctime,
-		    ZTOI(zp)->i_sb->s_time_gran);
+		ZTOI(zp)->i_ctime = zpl_inode_timestamp_truncate(vap->va_ctime,
+		    ZTOI(zp));
 		SA_ADD_BULK_ATTR(bulk, count, SA_ZPL_CTIME(zfsvfs), NULL,
 		    ctime, sizeof (ctime));
 	}
diff -Npur a/module/zfs/zpl_inode.c b/module/zfs/zpl_inode.c
--- a/module/zfs/zpl_inode.c	2020-02-06 03:51:22.000000000 -0500
+++ b/module/zfs/zpl_inode.c	2020-02-12 19:15:47.208101313 -0500
@@ -390,10 +390,8 @@ zpl_setattr(struct dentry *dentry, struc
 	vap->va_mtime = ia->ia_mtime;
 	vap->va_ctime = ia->ia_ctime;
 
-	if (vap->va_mask & ATTR_ATIME) {
-		ip->i_atime = zpl_inode_timespec_trunc(ia->ia_atime,
-		    ip->i_sb->s_time_gran);
-	}
+	if (vap->va_mask & ATTR_ATIME)
+		ip->i_atime = zpl_inode_timestamp_truncate(ia->ia_atime, ip);
 
 	cookie = spl_fstrans_mark();
 	error = -zfs_setattr(ip, vap, 0, cr);
```

**Comment by behlendorf** [comment]
Closing as a duplicate of #9961.  We'll make sure to include the kernel compatibility patches in the next 0.8.x release.

**Comment by ericek111** [comment]
@behlendorf Any idea when the next release could be out, please? I'm just asking for a rough timeframe, because atm my desktop with Arch Linux is stuck on 5.4.15 and I'd rather not compile and manage my own kernel unless absolutely necessary. Thanks!

**Comment by satmandu** [comment]
Also FYI there are new time related changes in 5.6rc3 which break building again: https://paste.ubuntu.com/p/FCyr8fXDnm/
