### ISSUE TITLE
Can't compile with 4.3-rc1 kernel

### ISSUE THREAD

**Issue by colorprint** [zfsonlinux/zfs#3799]
Tested with git master:

  CC [M]  /var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.o
In file included from include/linux/bitops.h:36:0,
                 from include/linux/kernel.h:10,
                 from include/linux/list.h:8,
                 from include/linux/module.h:9,
                 from /usr/src/spl-0.6.4.2/include/sys/sysmacros.h:28,
                 from /usr/src/spl-0.6.4.2/include/sys/types.h:29,
                 from /var/lib/dkms/zfs/0.6.4.2/build/include/sys/zfs_context.h:37,
                 from /var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:29:
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c: In function 'vdev_disk_physio_completion':
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:437:30: error: 'BIO_UPTODATE' undeclared (first use in this function)
  if (error == 0 && !test_bit(BIO_UPTODATE, &bio->bi_flags))
                              ^
./arch/x86/include/asm/bitops.h:336:25: note: in definition of macro 'test_bit'
  (__builtin_constant_p((nr))  \
                         ^
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:437:30: note: each undeclared identifier is reported only once for each function it appears in
  if (error == 0 && !test_bit(BIO_UPTODATE, &bio->bi_flags))
                              ^
./arch/x86/include/asm/bitops.h:336:25: note: in definition of macro 'test_bit'
  (__builtin_constant_p((nr))  \
                         ^
./arch/x86/include/asm/bitops.h:337:29: warning: passing argument 2 of 'constant_test_bit' from incompatible pointer type [-Wincompatible-pointer-types]
   ? constant_test_bit((nr), (addr)) \
                             ^
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:437:21: note: in expansion of macro 'test_bit'
  if (error == 0 && !test_bit(BIO_UPTODATE, &bio->bi_flags))
                     ^
./arch/x86/include/asm/bitops.h:308:28: note: expected 'const volatile long unsigned int *' but argument is of type 'unsigned int *'
 static __always_inline int constant_test_bit(long nr, const volatile unsigned long *addr)
                            ^
./arch/x86/include/asm/bitops.h:338:29: warning: passing argument 2 of 'variable_test_bit' from incompatible pointer type [-Wincompatible-pointer-types]
   : variable_test_bit((nr), (addr)))
                             ^
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:437:21: note: in expansion of macro 'test_bit'
  if (error == 0 && !test_bit(BIO_UPTODATE, &bio->bi_flags))
                     ^
./arch/x86/include/asm/bitops.h:314:19: note: expected 'const volatile long unsigned int *' but argument is of type 'unsigned int *'
 static inline int variable_test_bit(long nr, volatile const unsigned long *addr)
                   ^
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c: In function '__vdev_disk_physio':
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:579:28: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   dr->dr_bio[i]->bi_end_io = vdev_disk_physio_completion;
                            ^
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c: In function 'vdev_disk_io_flush':
/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.c:660:17: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
  bio->bi_end_io = vdev_disk_io_flush_completion;
                 ^
scripts/Makefile.build:258: recipe for target '/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.o' failed
make[5]: *** [/var/lib/dkms/zfs/0.6.4.2/build/module/zfs/vdev_disk.o] Error 1
scripts/Makefile.build:403: recipe for target '/var/lib/dkms/zfs/0.6.4.2/build/module/zfs' failed
make[4]: *** [/var/lib/dkms/zfs/0.6.4.2/build/module/zfs] Error 2
Makefile:1378: recipe for target '_module_/var/lib/dkms/zfs/0.6.4.2/build/module' failed
make[3]: *** [_module_/var/lib/dkms/zfs/0.6.4.2/build/module] Error 2
make[3]: Leaving directory '/usr/lib/modules/4.3.0-rc1-mainline/build'
Makefile:16: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.6.4.2/build/module'
Makefile:685: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.6.4.2/build'
Makefile:556: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by colorprint** [comment]
same issue with 4.3-rc2

**Comment by l1k** [comment]
Culprit is torvalds/linux@4246a0b63bd8f56a1469b12eafeb875b1041a451

**Comment by behlendorf** [comment]
Resolved by 784a7fe5d9a0c02e96f3ae019a08ecebee2a7018 which will be cherry-picked in to 0.6.5.2 release.
