### ISSUE TITLE
DKMS recompile fail on linux upgrade on Debian Jessie

### ISSUE THREAD

**Issue by ikus060** [zfsonlinux/zfs#5325]
On Debian Jessie (x64), everytime their is an upgrade of linux (package `linux-image-*`), the `zfs-dkms` and `slp-dkms` package is triggered to recompile the modules and it's failing. I'm having this problem for quite a while (a year or more).

Here are the log of a failed upgrade:

```
# sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages have been kept back:
  mod-pagespeed-stable
The following packages will be upgraded:
  bind9-host dnsutils libbind9-80 libdns88 libisc84 libisccc80 libisccfg82 liblwres80 libsystemd-login0 linux-compiler-gcc-4.6-x86 linux-headers-3.16.0-0.bpo.4-amd64 linux-headers-3.16.0-0.bpo.4-common linux-headers-3.2.0-4-common-rt linux-headers-3.2.0-4-rt-amd64
  linux-image-3.16.0-0.bpo.4-amd64 linux-image-3.2.0-4-amd64 linux-libc-dev
17 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/69.5 MB of archives.
After this operation, 25.6 kB of additional disk space will be used.
Do you want to continue [Y/n]? y
Reading changelogs... Done
Preconfiguring packages ...
(Reading database ... 63377 files and directories currently installed.)
Preparing to replace linux-image-3.16.0-0.bpo.4-amd64 3.16.36-1+deb8u1~bpo70+1 (using .../linux-image-3.16.0-0.bpo.4-amd64_3.16.36-1+deb8u2~bpo70+1_amd64.deb) ...
Unpacking replacement linux-image-3.16.0-0.bpo.4-amd64 ...
Preparing to replace linux-image-3.2.0-4-amd64 3.2.81-2 (using .../linux-image-3.2.0-4-amd64_3.2.82-1_amd64.deb) ...
Unpacking replacement linux-image-3.2.0-4-amd64 ...
Examining /etc/kernel/postrm.d .
run-parts: executing /etc/kernel/postrm.d/initramfs-tools 3.2.0-4-amd64 /boot/vmlinuz-3.2.0-4-amd64
run-parts: executing /etc/kernel/postrm.d/zz-update-grub 3.2.0-4-amd64 /boot/vmlinuz-3.2.0-4-amd64
Preparing to replace libsystemd-login0:amd64 44-11+deb7u4 (using .../libsystemd-login0_44-11+deb7u5_amd64.deb) ...
Unpacking replacement libsystemd-login0:amd64 ...
Preparing to replace bind9-host 1:9.8.4.dfsg.P1-6+nmu2+deb7u11 (using .../bind9-host_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u12_amd64.deb) ...
Unpacking replacement bind9-host ...
Preparing to replace dnsutils 1:9.8.4.dfsg.P1-6+nmu2+deb7u11 (using .../dnsutils_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u12_amd64.deb) ...
Unpacking replacement dnsutils ...
Preparing to replace libisc84 1:9.8.4.dfsg.P1-6+nmu2+deb7u11 (using .../libisc84_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u12_amd64.deb) ...
Unpacking replacement libisc84 ...
Preparing to replace libdns88 1:9.8.4.dfsg.P1-6+nmu2+deb7u11 (using .../libdns88_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u12_amd64.deb) ...
Unpacking replacement libdns88 ...
Preparing to replace libisccc80 1:9.8.4.dfsg.P1-6+nmu2+deb7u11 (using .../libisccc80_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u12_amd64.deb) ...
Unpacking replacement libisccc80 ...
Preparing to replace libisccfg82 1:9.8.4.dfsg.P1-6+nmu2+deb7u11 (using .../libisccfg82_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u12_amd64.deb) ...
Unpacking replacement libisccfg82 ...
Preparing to replace liblwres80 1:9.8.4.dfsg.P1-6+nmu2+deb7u11 (using .../liblwres80_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u12_amd64.deb) ...
Unpacking replacement liblwres80 ...
Preparing to replace libbind9-80 1:9.8.4.dfsg.P1-6+nmu2+deb7u11 (using .../libbind9-80_1%3a9.8.4.dfsg.P1-6+nmu2+deb7u12_amd64.deb) ...
Unpacking replacement libbind9-80 ...
Preparing to replace linux-compiler-gcc-4.6-x86 3.16.36-1+deb8u1~bpo70+1 (using .../linux-compiler-gcc-4.6-x86_3.16.36-1+deb8u2~bpo70+1_amd64.deb) ...
Unpacking replacement linux-compiler-gcc-4.6-x86 ...
Preparing to replace linux-headers-3.16.0-0.bpo.4-amd64 3.16.36-1+deb8u1~bpo70+1 (using .../linux-headers-3.16.0-0.bpo.4-amd64_3.16.36-1+deb8u2~bpo70+1_amd64.deb) ...
Unpacking replacement linux-headers-3.16.0-0.bpo.4-amd64 ...
Preparing to replace linux-headers-3.16.0-0.bpo.4-common 3.16.36-1+deb8u1~bpo70+1 (using .../linux-headers-3.16.0-0.bpo.4-common_3.16.36-1+deb8u2~bpo70+1_amd64.deb) ...
Unpacking replacement linux-headers-3.16.0-0.bpo.4-common ...
Preparing to replace linux-headers-3.2.0-4-rt-amd64 3.2.81-2 (using .../linux-headers-3.2.0-4-rt-amd64_3.2.82-1_amd64.deb) ...
Unpacking replacement linux-headers-3.2.0-4-rt-amd64 ...
Preparing to replace linux-headers-3.2.0-4-common-rt 3.2.81-2 (using .../linux-headers-3.2.0-4-common-rt_3.2.82-1_amd64.deb) ...
Unpacking replacement linux-headers-3.2.0-4-common-rt ...
Preparing to replace linux-libc-dev:amd64 3.16.36-1+deb8u1~bpo70+1 (using .../linux-libc-dev_3.16.36-1+deb8u2~bpo70+1_amd64.deb) ...
Unpacking replacement linux-libc-dev:amd64 ...
Processing triggers for man-db ...
Setting up linux-image-3.16.0-0.bpo.4-amd64 (3.16.36-1+deb8u2~bpo70+1) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-3.16.0-0.bpo.4-amd64
/etc/kernel/postinst.d/zz-update-grub:
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-3.16.0-0.bpo.4-amd64
Found initrd image: /boot/initrd.img-3.16.0-0.bpo.4-amd64
Found linux image: /boot/vmlinuz-3.2.0-4-amd64
Found initrd image: /boot/initrd.img-3.2.0-4-amd64
Found memtest86+ image: /boot/memtest86+.bin
Found memtest86+ multiboot image: /boot/memtest86+_multiboot.bin
Found Debian GNU/Linux (7.11) on /dev/sdd1
done
Setting up linux-image-3.2.0-4-amd64 (3.2.82-1) ...
Running depmod.
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/dkms 3.2.0-4-amd64 /boot/vmlinuz-3.2.0-4-amd64
Error! Your kernel headers for kernel 3.2.0-4-amd64 cannot be found.
Please install the linux-headers-3.2.0-4-amd64 package,
or use the --kernelsourcedir option to tell DKMS where it's located
Error! Your kernel headers for kernel 3.2.0-4-amd64 cannot be found.
Please install the linux-headers-3.2.0-4-amd64 package,
or use the --kernelsourcedir option to tell DKMS where it's located
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 3.2.0-4-amd64 /boot/vmlinuz-3.2.0-4-amd64
update-initramfs: Generating /boot/initrd.img-3.2.0-4-amd64
run-parts: executing /etc/kernel/postinst.d/pm-utils 3.2.0-4-amd64 /boot/vmlinuz-3.2.0-4-amd64
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 3.2.0-4-amd64 /boot/vmlinuz-3.2.0-4-amd64
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-3.16.0-0.bpo.4-amd64
Found initrd image: /boot/initrd.img-3.16.0-0.bpo.4-amd64
Found linux image: /boot/vmlinuz-3.2.0-4-amd64
Found initrd image: /boot/initrd.img-3.2.0-4-amd64
Found memtest86+ image: /boot/memtest86+.bin
Found memtest86+ multiboot image: /boot/memtest86+_multiboot.bin
Found Debian GNU/Linux (7.11) on /dev/sdd1
done
Setting up libsystemd-login0:amd64 (44-11+deb7u5) ...
Setting up libisc84 (1:9.8.4.dfsg.P1-6+nmu2+deb7u12) ...
Setting up libdns88 (1:9.8.4.dfsg.P1-6+nmu2+deb7u12) ...
Setting up libisccc80 (1:9.8.4.dfsg.P1-6+nmu2+deb7u12) ...
Setting up libisccfg82 (1:9.8.4.dfsg.P1-6+nmu2+deb7u12) ...
Setting up libbind9-80 (1:9.8.4.dfsg.P1-6+nmu2+deb7u12) ...
Setting up liblwres80 (1:9.8.4.dfsg.P1-6+nmu2+deb7u12) ...
Setting up bind9-host (1:9.8.4.dfsg.P1-6+nmu2+deb7u12) ...
Setting up dnsutils (1:9.8.4.dfsg.P1-6+nmu2+deb7u12) ...
Setting up linux-compiler-gcc-4.6-x86 (3.16.36-1+deb8u2~bpo70+1) ...
Setting up linux-headers-3.16.0-0.bpo.4-common (3.16.36-1+deb8u2~bpo70+1) ...
Setting up linux-headers-3.16.0-0.bpo.4-amd64 (3.16.36-1+deb8u2~bpo70+1) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 3.16.0-0.bpo.4-amd64
Setting up linux-headers-3.2.0-4-common-rt (3.2.82-1) ...
Setting up linux-headers-3.2.0-4-rt-amd64 (3.2.82-1) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 3.2.0-4-rt-amd64
Error! Bad return status for module build on kernel: 3.2.0-4-rt-amd64 (x86_64)
Consult /var/lib/dkms/spl/0.6.5.7/build/make.log for more information.
configure: error: 
    *** Please make sure the kmod spl devel <kernel> package for your
    *** distribution is installed then try again.  If that fails you
    *** can specify the location of the spl objects with the
    *** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 3.2.0-4-rt-amd64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.7/build/make.log for more information.
Setting up linux-libc-dev:amd64 (3.16.36-1+deb8u2~bpo70+1) ...
```

Here the content of `/var/lib/dkms/spl/0.6.5.7/build/make.log`

```
DKMS make.log for spl-0.6.5.7 for kernel 3.2.0-4-rt-amd64 (x86_64)
Sun Oct 23 08:17:35 EDT 2016
make  all-recursive
make[1]: Entering directory `/var/lib/dkms/spl/0.6.5.7/build'
Making all in module
make[2]: Entering directory `/var/lib/dkms/spl/0.6.5.7/build/module'
make -C /lib/modules/3.2.0-4-rt-amd64/build SUBDIRS=`pwd`  O=/lib/modules/3.2.0-4-rt-amd64/build CONFIG_SPL=m modules
make[3]: Entering directory `/usr/src/linux-headers-3.2.0-4-rt-amd64'
  CC [M]  /var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-vmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-thread.o
  CC [M]  /var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-taskq.o
  CC [M]  /var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.o
In file included from /var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c:27:0:
/var/lib/dkms/spl/0.6.5.7/build/include/sys/rwlock.h: In function ‘spl_rw_set_owner’:
/var/lib/dkms/spl/0.6.5.7/build/include/sys/rwlock.h:55:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.5.7/build/include/sys/rwlock.h:57:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.5.7/build/include/sys/rwlock.h: In function ‘spl_rw_clear_owner’:
/var/lib/dkms/spl/0.6.5.7/build/include/sys/rwlock.h:65:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.5.7/build/include/sys/rwlock.h:67:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.5.7/build/include/sys/rwlock.h: In function ‘rw_owner’:
/var/lib/dkms/spl/0.6.5.7/build/include/sys/rwlock.h:76:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.5.7/build/include/sys/rwlock.h:78:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c: In function ‘__rwsem_wake_one_writer_locked’:
/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c:56:12: error: ‘struct rw_semaphore’ has no member named ‘activity’
/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c:58:18: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c: In function ‘__up_read_locked’:
/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c:73:18: error: ‘struct rw_semaphore’ has no member named ‘activity’
/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c:73:53: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c: In function ‘__down_write_trylock_locked’:
/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c:84:16: error: ‘struct rw_semaphore’ has no member named ‘activity’
/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c:84:50: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.c:85:20: error: ‘struct rw_semaphore’ has no member named ‘activity’
make[7]: *** [/var/lib/dkms/spl/0.6.5.7/build/module/spl/spl-rwlock.o] Error 1
make[6]: *** [/var/lib/dkms/spl/0.6.5.7/build/module/spl] Error 2
make[5]: *** [_module_/var/lib/dkms/spl/0.6.5.7/build/module] Error 2
make[4]: *** [sub-make] Error 2
make[3]: *** [all] Error 2
make[3]: Leaving directory `/usr/src/linux-headers-3.2.0-4-rt-amd64'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.5.7/build/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/dkms/spl/0.6.5.7/build'
make: *** [all] Error 2
```

To work around this problem I need to uninstall zfs, then reinstall as follow:

```
sudo apt-get remove zfs-dkms spl-dkms
sudo apt-get install debian-zfs
```

**Comment by tj90241** [comment]
Do you have the `linux-headers` package installed? Based on the log messages, it seems you do not. This may be causing the problem.

**Comment by ikus060** [comment]
Look more closely to the log. `apt-get` is upgrading the follow packages: `linux-headers-3.16.0-0.bpo.4-amd64 linux-headers-3.16.0-0.bpo.4-common linux-headers-3.2.0-4-common-rt linux-headers-3.2.0-4-rt-amd64`

Maybe the issue is I have too many linux headers ?

**Comment by gmelikov** [comment]
As i can see, you have a problem with linux-headers-3.2.0-4-common-rt package, as i look at https://packages.debian.org/search?keywords=linux-headers-3.2.0-4-common , it's described as `wheezy` package, not `jessie` one. 

I recommend you to delete any unneeded kernels and headers.

**Comment by gmelikov** [comment]
Additionally, if you don't boot from ZFS, you can install ZFS packages from jessie-backports now, [here](https://github.com/zfsonlinux/zfs/wiki/Debian#installation) is the instruction.

**Comment by tj90241** [comment]
In addition to what @gmelikov said, I don't think you have the right linux-headers package:

apt-get is installing these:
`linux-headers-3.16.0-0.bpo.4-amd64`
`linux-headers-3.16.0-0.bpo.4-common`
`linux-headers-3.2.0-4-common-rt`
`linux-headers-3.2.0-4-rt-amd64`

Notice that you do not have the important one, `linux-headers-3.2.0-4-amd64`.

I agree that the easiest thing at this point is to just `apt-get purge linux.*3.2.*`, so you only have jessie packages on your system. At least that will clear out some of the noise before proceeding (either trying to install the dkms sources again, or installing ZFS from jessie-backports).

**Comment by ikus060** [comment]
Yep, I've clean-up the packages:
```
$ dpkg --get-selections | grep headers
linux-headers-3.16.0-0.bpo.4-amd64		install
linux-headers-3.16.0-0.bpo.4-common		install
linux-headers-amd64				install
```

**Comment by gmelikov** [comment]
Closing as resolved, reopen the issue if needed.
