### ISSUE TITLE
arc_reclaim stuck in state D

### ISSUE THREAD

**Issue by chrekh** [zfsonlinux/zfs#4633]
After update of zfs today I noticed the load-value staying on 1 constantly.
I found that it's arc_reclaim getting stuck in stade D

```
$ ps auxr
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       634  0.0  0.0      0     0 ?        D    23:38   0:00 [arc_reclaim]
che       7484  0.0  0.0  14912  2016 pts/0    R+   23:40   0:00 ps auxr
```

I have bisected this to commit ae6d0c601eb863f8275bf4ec841fbebf774c3d65

I have also verified that reverting ae6d0c6 on top of 04bc461 solves the issue.

I'm using kernel 4.5.4

**Comment by tuxoko** [comment]
@chrekh 
Are there any issue other than the constant D state?

**Comment by behlendorf** [comment]
Thanks for filing this.  This was caused by the switch to `cv_timedwait_hires()` from `cv_timedwait_sig()`.  The *_sig versions sleep interruptibly the other sleep uninterruptibly which accounts for the load average.  The straight forward thing to do here is add a `cv_timedwait_hires_sig()` function.

**Comment by chrekh** [comment]
@tuxoko: No, not any I have noticed yet.

I tried e371c3f, but that fail to build.

```
/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/zfs/arc.c: In function ‘arc_reclaim_thread’:
/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/zfs/arc.c:3509:11: error: implicit declaration of function ‘cv_timedwait_sig_hires’ [-Werror=implicit-function-declaration]eclaim_thread_cv,
           ^
```

**Comment by behlendorf** [comment]
@chrekh the build failed because the change depends on zfsonlinux/spl#548.  This is a straight forward fix so both of these patch will very likely get applied today.

**Comment by chrekh** [comment]
I have now tried with tuxoko/spl@a5bdd0f & e371c3f
It builds fine, but I still have arc_reclaim stuck in state D

**Comment by tuxoko** [comment]
usleep_range will set TASK_UNINTERRUPTIBLE...

**Comment by behlendorf** [comment]
We could use `schedule_timeout()` here when we're sleeping for over MAX_UDELAY_MS.

**Comment by tuxoko** [comment]
I've updated zfsonlinux/spl#548, this time it should fix it.

**Comment by chrekh** [comment]
@tuxoko: Yes, it did.

**Comment by behlendorf** [comment]
@chrekh thanks for the quick confirmation.  The automated testing looks good as well, @tuxoko this LGTM if you're happy with the patches I'll get them merged.

**Comment by tuxoko** [comment]
Yes.
