### ISSUE TITLE
TASKQID_INVALID

### ISSUE THREAD

**Issue by MasterCATZ** [zfsonlinux/zfs#5987]
### System information

Type                                | Version/Name
Distribution Name       | Ubuntu xenial
Distribution Version    | 16.04
Linux Kernel                 |  4.10.8-041008-generic
Architecture                 | x86_64
ZFS Version                  | 0.6.5.9
SPL Version                  | 0.6.5.9
DKMS Version | 2.3-3
spl-dkms | 0.6.5.9

### Describe the problem you're observing

Trying to get working zfs for kernel 4.10 , 
I can never seem to get 16.04 to work with its built-in ZFS (0.6.5.6-0ubuntu16)?

The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.

modprobe: FATAL: Module zfs not found in directory /lib/modules/4.xxx-generic

ZFS 0.6.5.6 does not seem to install any higher than 4.8.17 Kernel 
4.8.7 was my last working install 

also 
https://github.com/zfsonlinux/zfs/issues/3037
https://github.com/zfsonlinux/zfs/issues/4720

zed was still going 100% CPU constantly after reboot and needing forced pkill -9 

### Describe how to reproduce the problem

sudo apt-get install build-essential autoconf libtool gawk alien fakeroot linux-headers-$(uname -r)
sudo apt-get install zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libdevmapper-dev

git clone https://github.com/zfsonlinux/zfs
cd ../zfs
git checkout master
sh autogen.sh
./configure
make -s -j$(nproc)

### Include any warning/errors/backtraces from the system logs

```
Making all in initramfs
Making all in module
In file included from /mnt/Install/gitclone/zfs/include/sys/zfs_znode.h:41:0,
                 from /mnt/Install/gitclone/zfs/module/zcommon/zfs_prop.c:35:
/mnt/Install/gitclone/zfs/include/sys/zfs_rlock.h: In function ‘zfs_rlock_destroy’:
/mnt/Install/gitclone/zfs/include/sys/zfs_rlock.h:110:2: error: conversion to non-scalar type requested
  mutex_destroy(&zrl->zr_mutex);
  ^
/mnt/Install/gitclone/zfs/include/sys/zfs_rlock.h:110:2: error: aggregate value used where an integer was expected
/mnt/Install/gitclone/zfs/include/sys/zfs_rlock.h:110:2: error: conversion to non-scalar type requested
/mnt/Install/gitclone/zfs/include/sys/zfs_rlock.h:110:2: error: cannot convert to a pointer type
scripts/Makefile.build:294: recipe for target '/mnt/Install/gitclone/zfs/module/zcommon/zfs_prop.o' failed
make[5]: *** [/mnt/Install/gitclone/zfs/module/zcommon/zfs_prop.o] Error 1
scripts/Makefile.build:553: recipe for target '/mnt/Install/gitclone/zfs/module/zcommon' failed
make[4]: *** [/mnt/Install/gitclone/zfs/module/zcommon] Error 2
make[4]: *** Waiting for unfinished jobs....
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c: In function ‘kcf_resubmit_request’:
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:564:7: error: ‘TASKQID_INVALID’ undeclared (first use in this function)
       TASKQID_INVALID) {
       ^
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:564:7: note: each undeclared identifier is reported only once for each function it appears in
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c: In function ‘kcf_submit_request’:
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:785:8: error: ‘TASKQID_INVALID’ undeclared (first use in this function)
        TASKQID_INVALID) {
        ^
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c: In function ‘kcf_sreq_cache_destructor’:
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:992:2: error: conversion to non-scalar type requested
  mutex_destroy(&sreq->sn_lock);
  ^
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:992:2: error: aggregate value used where an integer was expected
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:992:2: error: conversion to non-scalar type requested
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:992:2: error: cannot convert to a pointer type
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c: In function ‘kcf_areq_cache_destructor’:
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:1021:2: error: conversion to non-scalar type requested
  mutex_destroy(&areq->an_lock);
  ^
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:1021:2: error: aggregate value used where an integer was expected
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:1021:2: error: conversion to non-scalar type requested
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:1021:2: error: cannot convert to a pointer type
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c: In function ‘kcf_context_cache_destructor’:
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:1048:2: error: conversion to non-scalar type requested
  mutex_destroy(&kctx->kc_in_use_lock);
  ^
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:1048:2: error: aggregate value used where an integer was expected
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:1048:2: error: conversion to non-scalar type requested
/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.c:1048:2: error: cannot convert to a pointer type
scripts/Makefile.build:294: recipe for target '/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.o' failed
make[5]: *** [/mnt/Install/gitclone/zfs/module/icp/core/kcf_sched.o] Error 1
make[5]: *** Waiting for unfinished jobs....
scripts/Makefile.build:553: recipe for target '/mnt/Install/gitclone/zfs/module/icp' failed
make[4]: *** [/mnt/Install/gitclone/zfs/module/icp] Error 2
Makefile:1496: recipe for target '_module_/mnt/Install/gitclone/zfs/module' failed
make[3]: *** [_module_/mnt/Install/gitclone/zfs/module] Error 2
Makefile:21: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
Makefile:716: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:585: recipe for target 'all' failed
make: *** [all] Error 2
aio@aio:/mnt/Install/gitclone/zfs$ 


```
-->

**Comment by MasterCATZ** [comment]
Ubuntu 17.04 
sudo apt install zfs-dkms

gave me working zfs with kernel 4.10 
now to break the system again to try kernel 4.11

so i can make use of ryzen cpu ...
