### ISSUE TITLE
Cannot compile on Ubuntu 14.04.5 with kernel 4.4.0-49

### ISSUE THREAD

**Issue by dimez** [zfsonlinux/zfs#5408]
From make.log:
  CC [M]  /var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.o
/var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.c: In function ‘__zpl_xattr_acl_set_access’:
/var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.c:1293:4: warning: passing argument 1 of ‘posix_acl_valid’ from incompatible pointer type [enabled by default]
    error = posix_acl_valid(acl);
    ^
In file included from /var/lib/dkms/zfs/0.6.5.7/build/include/linux/vfs_compat.h:204:0,
                 from /var/lib/dkms/zfs/0.6.5.7/build/include/sys/zpl.h:37,
                 from /var/lib/dkms/zfs/0.6.5.7/build/include/sys/zfs_vnops.h:34,
                 from /var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.c:81:
include/linux/posix_acl.h:84:12: note: expected ‘struct user_namespace *’ but argument is of type ‘struct posix_acl *’
 extern int posix_acl_valid(struct user_namespace *, const struct posix_acl *);
            ^
/var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.c:1293:4: error: too few arguments to function ‘posix_acl_valid’
    error = posix_acl_valid(acl);
    ^
In file included from /var/lib/dkms/zfs/0.6.5.7/build/include/linux/vfs_compat.h:204:0,
                 from /var/lib/dkms/zfs/0.6.5.7/build/include/sys/zpl.h:37,
                 from /var/lib/dkms/zfs/0.6.5.7/build/include/sys/zfs_vnops.h:34,
                 from /var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.c:81:
include/linux/posix_acl.h:84:12: note: declared here
 extern int posix_acl_valid(struct user_namespace *, const struct posix_acl *);
            ^
/var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.c: In function ‘__zpl_xattr_acl_set_default’:
/var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.c:1333:4: warning: passing argument 1 of ‘posix_acl_valid’ from incompatible pointer type [enabled by default]
    error = posix_acl_valid(acl);
    ^
In file included from /var/lib/dkms/zfs/0.6.5.7/build/include/linux/vfs_compat.h:204:0,
                 from /var/lib/dkms/zfs/0.6.5.7/build/include/sys/zpl.h:37,
                 from /var/lib/dkms/zfs/0.6.5.7/build/include/sys/zfs_vnops.h:34,
                 from /var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.c:81:
include/linux/posix_acl.h:84:12: note: expected ‘struct user_namespace *’ but argument is of type ‘struct posix_acl *’
 extern int posix_acl_valid(struct user_namespace *, const struct posix_acl *);
            ^
/var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.c:1333:4: error: too few arguments to function ‘posix_acl_valid’
    error = posix_acl_valid(acl);
    ^
In file included from /var/lib/dkms/zfs/0.6.5.7/build/include/linux/vfs_compat.h:204:0,
                 from /var/lib/dkms/zfs/0.6.5.7/build/include/sys/zpl.h:37,
                 from /var/lib/dkms/zfs/0.6.5.7/build/include/sys/zfs_vnops.h:34,
                 from /var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.c:81:
include/linux/posix_acl.h:84:12: note: declared here
 extern int posix_acl_valid(struct user_namespace *, const struct posix_acl *);
            ^
make[5]: *** [/var/lib/dkms/zfs/0.6.5.7/build/module/zfs/zpl_xattr.o] Error 1
make[4]: *** [/var/lib/dkms/zfs/0.6.5.7/build/module/zfs] Error 2
make[3]: *** [_module_/var/lib/dkms/zfs/0.6.5.7/build/module] Error 2
make[3]: Leaving directory `/usr/src/linux-headers-4.4.0-49-generic'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/zfs/0.6.5.7/build/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/dkms/zfs/0.6.5.7/build'
make: *** [all] Error 2

**Comment by gmelikov** [comment]
Did you use [this](https://github.com/zfsonlinux/zfs/wiki/Building-ZFS) instruction?

**Comment by dimez** [comment]
Hello
Thank you for fast reply
No, I use official zfs-native PPA for several years and all ok except kernel 4.4.0-49:
\# cat /etc/apt/sources.list.d/zfs-native-stable-trusty.list
deb http://ppa.launchpad.net/zfs-native/stable/ubuntu trusty main
\# deb-src http://ppa.launchpad.net/zfs-native/stable/ubuntu trusty main

Sorry, I can't use unstable version because it's working server with several VM's.

**Comment by gmelikov** [comment]
Last stable version is 0.6.5.8,  i see 0.6.5.7 in your logs.

Oh, as i remember 4.4 kernel support was added in 0.6.5.8, just update it.

**Comment by kpande** [comment]
please use mailing list or IRC for support requests: http://list.zfsonlinux.org

**Comment by dimez** [comment]
> Last stable version is 0.6.5.8, i see 0.6.5.7 in your logs

I can't update to 0.6.5.8. Last version in PPA is 0.6.5.7.
